import type { EventoDaAgenda } from "../components/AgendaFiltravel";

export const responsaveisDemo = Array.from({length:12},(_,i)=>({id:`demo-pessoa-${i+1}`,nome:["Ana Souza","Bruno Lima","Carla Santos","Diego Alves","Elisa Costa","Fabio Rocha","Gabriela Luz","Hugo Martins","Iara Ribeiro","Joao Silva","Laura Reis","Marcos Dias"][i]}));
export function eventosDemo(hoje: string): EventoDaAgenda[] {
  return Array.from({length:24},(_,i)=>{
    const data=new Date(`${hoje}T12:00:00Z`);data.setUTCDate(data.getUTCDate()+Math.floor(i/3));
    return {id:`demo-evento-${i+1}`,data_evento:data.toISOString().slice(0,10),horario:["12:00","18:30","20:00"][i%3],horario_texto:null,horario_saida:["10:30","17:00","18:30"][i%3],cliente_nome:`Evento demonstrativo ${String(i+1).padStart(2,"0")}`,cliente_telefone:null,responsavel_id:i%3===0?null:responsaveisDemo[i%12].id,responsavel_nome:i%3===0?null:responsaveisDemo[i%12].nome,inteiros:30+(i%8)*10,meios:i%4,total_do_evento:1800+i*135,situacao:["Agendado","Cobrar sinal","Confirmar nº de pessoas"][i%3],cidade:["Porto Alegre","Canoas","Gravataí"][i%3],bairro:["Centro","Moinhos de Vento","Bela Vista"][i%3],endereco:`Rua de demonstração, ${100+i}`,tipo_evento_nome:["Aniversário","Casamento","Confraternização"][i%3],modelo_forno_nome:i%2?"Gás":"Elétrico",modelo_rodizio_nome:i%2?"Rodízio Premium":"Rodízio Clássico",codigo_legado:`DEMO-${i+1}`,atencao:i%4===0};
  });
}
export const pessoasDemo = Array.from({length:30},(_,i)=>({id:`demo-pessoa-${i+1}`,nome:i<12?responsaveisDemo[i].nome:`Integrante demonstrativo ${i+1}`,telefone:null,foto_url:`/demo/pessoas/${i+1}.jpg`,nota:Math.round((5-(i%6)*0.1)*10)/10,avaliacoes:Math.max(0,30-i),bloqueado:i===29,perfil:{garcom:i%4!==0||i%8===0,forno:i%4===0,endereco:`Residencia demonstrativa ${i+1}`,bairro:["Centro","Sarandi","Moinhos de Vento"][i%3],cidade:"Porto Alegre",latitude:-30.005-(i%6)*0.008,longitude:-51.12-Math.floor(i/6)*0.015,transporte:null,meios_transporte:[['moto'],['carro'],['van'],['uber','onibus'],['empresa']][i%5],veiculos:i%5<3?[["moto"],["carro"],["van"]][i%5]:[],cnh_categorias:i%5===0?["A"]:i%5===1?["B"]:i%5===2?["B","D"]:[],apresentacao:i%4===0?"Experiencia em forno e lideranca de eventos.":"Atendimento e organizacao do servico."}}));
