"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { CreditCard, Wallet, UsersRound } from "lucide-react";
import { formatBRL } from "../../lib/moeda";
import { PaginacaoPorParametro } from "../painel/PaginacaoPorParametro";

export type MovimentoHoje = { origem_id: string; dia: string; natureza: "entrada" | "saida"; descricao: string | null; valor: number | string };
export type ResumoCaixa = { movimentos: number; entradas: number | string; saidas: number | string; saldo: number | string };
export type Acerto = { id: string; usuario_id: string; evento_id: string; evento: { data_evento: string; codigo_legado: string | null } | null; valor: number | string | null; chave_pix_retrato: string | null; estado: string; criado_em: string };
export type EscalaFreelance = { id: string; usuario_id: string; evento_id: string; data_evento: string; codigo_legado: string | null; nome: string };
export type Cartao = { id: string; nome: string; fechamento_dia: number; vencimento_dia: number };
export type Fatura = { cartao_id: string; nome: string; competencia: string; vencimento: string; total: number | string; pago: number | string };
const FREELANCE_POR_PAGINA = 30;
const campo = "w-full rounded-lg bg-surface-container px-3 py-2 text-on-surface";
function hojeBrasil() { return new Date().toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" }); }

export function GestaoFinanceira({ movimentos, resumo, acertos, totalAcertos, paginaAcertos, escalas, totalEscalas, paginaEscalas, cartoes, faturas, pessoas }: { movimentos: MovimentoHoje[]; resumo: ResumoCaixa; acertos: Acerto[]; totalAcertos: number; paginaAcertos: number; escalas: EscalaFreelance[]; totalEscalas: number; paginaEscalas: number; cartoes: Cartao[]; faturas: Fatura[]; pessoas: { id: string; nome: string }[] }) {
  const router = useRouter(); const [erro, setErro] = useState(""); const [ocupado, setOcupado] = useState(false);
  const [movimentosAtuais, setMovimentosAtuais] = useState(movimentos); const [paginaMovimentos, setPaginaMovimentos] = useState(1); const [carregandoMovimentos, setCarregandoMovimentos] = useState(false);
  useEffect(() => { setMovimentosAtuais(movimentos); setPaginaMovimentos(1); }, [movimentos]);
  const [nome, setNome] = useState(""); const [fechamento, setFechamento] = useState(20); const [vencimento, setVencimento] = useState(5);
  const [cartao, setCartao] = useState(""); const [data, setData] = useState(hojeBrasil); const [descricao, setDescricao] = useState(""); const [valor, setValor] = useState("");
  const [selecionados, setSelecionados] = useState<string[]>([]); const [comprovante, setComprovante] = useState(""); const [dataAcerto, setDataAcerto] = useState(hojeBrasil);
  const [escalasConcluidas, setEscalasConcluidas] = useState<string[]>([]);
  useEffect(() => setSelecionados([]), [paginaAcertos]);
  useEffect(() => setEscalasConcluidas([]), [paginaEscalas]);
  const [integrante, setIntegrante] = useState(""); const [freelanceAtivo, setFreelanceAtivo] = useState(true); const [valorFreelance, setValorFreelance] = useState(""); const [pix, setPix] = useState("");
  const [faturaEscolhida, setFaturaEscolhida] = useState(""); const [valorFatura, setValorFatura] = useState("");
  async function enviar(dados: Record<string, unknown>) {
    setErro(""); setOcupado(true);
    try { const resposta = await fetch("/api/operacao/financeiro", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(dados) }); const corpo = await resposta.json(); if (!resposta.ok) throw new Error(corpo.mensagem); router.refresh(); return true; }
    catch (falha) { setErro(falha instanceof Error ? falha.message : "Não foi possível salvar"); return false; }
    finally { setOcupado(false); }
  }
  async function abrirPaginaMovimentos(pagina: number) {
    if (pagina < 1 || pagina > Math.ceil(resumo.movimentos / 50)) return;
    setCarregandoMovimentos(true); setErro("");
    try {
      const resposta = await fetch(`/api/operacao/financeiro/movimentos?dia=${hojeBrasil()}&pagina=${pagina}`, { cache: "no-store" });
      if (!resposta.ok) throw new Error("Não foi possível carregar as movimentações.");
      const dados = await resposta.json() as { movimentos: MovimentoHoje[] };
      setMovimentosAtuais(dados.movimentos); setPaginaMovimentos(pagina);
    } catch (falha) { setErro(falha instanceof Error ? falha.message : "Falha ao carregar movimentações"); }
    finally { setCarregandoMovimentos(false); }
  }
  const pendentes = acertos.filter(a => a.estado === "pendente");
  const acertosSelecionados = pendentes.filter(a => selecionados.includes(a.id));
  const totalSelecionado = acertosSelecionados.reduce((n, a) => n + Number(a.valor ?? 0), 0);
  return <div className="space-y-8">
    <section className="space-y-3 rounded-2xl bg-surface-container-low p-4">
      <h2 className="font-title-lg">Confirmar trabalho realizado</h2>
      <p className="text-sm text-on-surface-variant">Selecione apenas freelancers que trabalharam nos eventos encerrados. A confirmação gera os acertos para o financeiro, mesmo sem avaliação do cliente.</p>
      {escalas.length ? <>
        <div className="grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2 xl:grid-cols-3">{escalas.map((escala) => <label key={escala.id} className="flex items-start gap-3 rounded-xl bg-surface-container-lowest p-3 text-sm"><input type="checkbox" checked={escalasConcluidas.includes(escala.id)} onChange={(e) => setEscalasConcluidas((atual) => e.target.checked ? [...atual, escala.id] : atual.filter((id) => id !== escala.id))} /><span><strong className="block">{escala.nome}</strong>Evento {escala.codigo_legado ?? escala.evento_id.slice(0, 8)} · {escala.data_evento.split("-").reverse().join("/")}</span></label>)}</div>
        <button type="button" disabled={ocupado || escalasConcluidas.length === 0} onClick={() => void enviar({ acao: "concluir_freelance", ids: escalasConcluidas }).then((ok) => { if (ok) setEscalasConcluidas([]); })} className="rounded-xl bg-primary px-4 py-2 text-on-primary disabled:opacity-40">Confirmar {escalasConcluidas.length} {escalasConcluidas.length === 1 ? "participação" : "participações"}</button>
      </> : <p className="text-sm text-on-surface-variant">Nenhuma participação freelance aguardando confirmação.</p>}
      {totalEscalas > FREELANCE_POR_PAGINA && <PaginacaoPorParametro parametro="escalas" pagina={paginaEscalas} total={totalEscalas} porPagina={FREELANCE_POR_PAGINA} rotulo="Escalas freelance" />}
    </section>
    <section className="space-y-3"><h2 className="flex items-center gap-2 font-headline-sm text-headline-sm"><Wallet size={20} />Hoje · {hojeBrasil().split("-").reverse().join("/")}</h2><div className="grid gap-3 sm:grid-cols-3">{[["Entradas", resumo.entradas], ["Saídas", resumo.saidas], ["Saldo do dia", resumo.saldo]].map(([nome, numero]) => <div key={String(nome)} className="rounded-2xl bg-surface-container-low p-4"><p className="text-sm text-on-surface-variant">{nome}</p><strong className="text-xl">{formatBRL(Number(numero))}</strong></div>)}</div><div className="rounded-2xl bg-surface-container-lowest p-4">{movimentosAtuais.length ? movimentosAtuais.map((m) => <div key={m.origem_id} className="flex justify-between gap-4 border-t border-outline-variant/30 py-2 first:border-0"><span>{m.descricao ?? (m.natureza === "entrada" ? "Recebimento" : "Pagamento")}</span><strong className={m.natureza === "entrada" ? "text-tertiary" : "text-primary"}>{formatBRL(Number(m.valor))}</strong></div>) : <p className="text-on-surface-variant">Nenhuma movimentação registrada hoje.</p>}</div>{resumo.movimentos > 50 && <div className="flex items-center justify-between gap-3 text-sm"><span>{resumo.movimentos} movimentações · página {paginaMovimentos} de {Math.ceil(resumo.movimentos / 50)}</span><div className="flex gap-2"><button type="button" disabled={carregandoMovimentos || paginaMovimentos <= 1} onClick={() => void abrirPaginaMovimentos(paginaMovimentos - 1)} className="rounded-lg bg-surface-container px-3 py-2 disabled:opacity-40">Anterior</button><button type="button" disabled={carregandoMovimentos || paginaMovimentos >= Math.ceil(resumo.movimentos / 50)} onClick={() => void abrirPaginaMovimentos(paginaMovimentos + 1)} className="rounded-lg bg-surface-container px-3 py-2 disabled:opacity-40">Próxima</button></div></div>}</section>
    <section className="space-y-3"><h2 className="flex items-center gap-2 font-headline-sm text-headline-sm"><UsersRound size={20} />Freelancers a pagar <span className="rounded-full bg-primary px-2 text-sm text-on-primary">{totalAcertos}</span></h2><p className="text-sm text-on-surface-variant">Eventos concluídos geram acertos individuais. Selecione vários da mesma pessoa para pagar o total em uma transferência.</p>{pendentes.length ? <div className="space-y-2">{pendentes.map(a => <label key={a.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-surface-container-low p-3"><input type="checkbox" checked={selecionados.includes(a.id)} disabled={a.valor === null || !a.chave_pix_retrato} onChange={e => setSelecionados(atual => e.target.checked ? [...atual, a.id] : atual.filter(id => id !== a.id))} /><span className="min-w-40 flex-1"><strong>{pessoas.find(p => p.id === a.usuario_id)?.nome ?? "Integrante"}</strong><small className="block text-on-surface-variant">Evento {a.evento?.codigo_legado ?? a.evento_id.slice(0, 8)}{a.evento?.data_evento ? ` - ${a.evento.data_evento.split("-").reverse().join("/")}` : ""} · Pix: {a.chave_pix_retrato ?? "cadastro pendente"}</small></span><strong>{a.valor === null ? "Valor pendente" : formatBRL(Number(a.valor))}</strong></label>)}<div className="flex flex-wrap items-end gap-3"><label className="text-sm">Data do pagamento<input required type="date" className={campo} value={dataAcerto} onChange={e => setDataAcerto(e.target.value)} /></label><label className="text-sm">Comprovante/referência<input className={campo} value={comprovante} onChange={e => setComprovante(e.target.value)} maxLength={300} /></label><button disabled={ocupado || !dataAcerto || !selecionados.length || new Set(acertosSelecionados.map(a => `${a.usuario_id}|${a.chave_pix_retrato}`)).size !== 1} onClick={() => void enviar({ acao: "quitar_freelance", ids: selecionados, data: dataAcerto, comprovante }).then(ok => { if (ok) setSelecionados([]); })} className="rounded-xl bg-primary px-4 py-2 text-on-primary disabled:opacity-40">Marcar {formatBRL(totalSelecionado)} como pago</button></div>{selecionados.length > 0 && new Set(acertosSelecionados.map(a => `${a.usuario_id}|${a.chave_pix_retrato}`)).size !== 1 && <p className="text-sm text-primary">Selecione acertos da mesma pessoa e com a mesma chave Pix.</p>}</div> : <p className="rounded-xl bg-surface-container-low p-4 text-on-surface-variant">Nenhum acerto pendente.</p>}{totalAcertos > FREELANCE_POR_PAGINA && <PaginacaoPorParametro parametro="acertos" pagina={paginaAcertos} total={totalAcertos} porPagina={FREELANCE_POR_PAGINA} rotulo="Acertos freelance" />}</section>
    <section className="space-y-3"><h2 className="flex items-center gap-2 font-headline-sm text-headline-sm"><CreditCard size={20} />Cartões e faturas</h2><div className="grid gap-4 lg:grid-cols-2"><form onSubmit={(e: FormEvent) => { e.preventDefault(); void enviar({ acao: "cartao", nome, fechamento, vencimento }).then(ok => { if (ok) setNome(""); }); }} className="grid gap-3 rounded-2xl bg-surface-container-low p-4 sm:grid-cols-3"><label className="text-sm sm:col-span-3">Cadastrar cartão<input className={campo} value={nome} onChange={e => setNome(e.target.value)} required placeholder="Nome de identificação" /></label><label className="text-sm">Fecha dia<input className={campo} type="number" min={1} max={28} value={fechamento} onChange={e => setFechamento(Number(e.target.value))} /></label><label className="text-sm">Vence dia<input className={campo} type="number" min={1} max={28} value={vencimento} onChange={e => setVencimento(Number(e.target.value))} /></label><button disabled={ocupado} className="self-end rounded-xl bg-primary px-3 py-2 text-on-primary disabled:opacity-50">Cadastrar</button></form><form onSubmit={(e: FormEvent) => { e.preventDefault(); void enviar({ acao: "compra", cartao, data, descricao, valor: Number(valor) }).then(ok => { if (ok) { setDescricao(""); setValor(""); } }); }} className="grid gap-3 rounded-2xl bg-surface-container-low p-4 sm:grid-cols-2"><label className="text-sm">Cartão<select className={campo} value={cartao} onChange={e => setCartao(e.target.value)} required><option value="">Escolha</option>{cartoes.map(c => <option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label className="text-sm">Data<input className={campo} type="date" value={data} onChange={e => setData(e.target.value)} required /></label><label className="text-sm">Descrição<input className={campo} value={descricao} onChange={e => setDescricao(e.target.value)} required /></label><label className="text-sm">Valor (R$)<input className={campo} type="number" min="0.01" step="0.01" value={valor} onChange={e => setValor(e.target.value)} required /></label><button disabled={ocupado || !cartao} className="rounded-xl bg-primary px-3 py-2 text-on-primary disabled:opacity-50 sm:col-span-2">Registrar compra</button></form></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{faturas.map(f => <article key={`${f.cartao_id}-${f.competencia}`} className="rounded-xl bg-surface-container-lowest p-4 ring-1 ring-outline-variant/30"><strong>{f.nome}</strong><p className="text-sm text-on-surface-variant">Fatura {f.competencia.slice(0, 7)} · vence {f.vencimento.split("-").reverse().join("/")}</p><div className="mt-3 flex justify-between"><span>{formatBRL(Number(f.total))}</span><span className="text-on-surface-variant">Pago {formatBRL(Number(f.pago))}</span></div></article>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2">
      <form onSubmit={e => { e.preventDefault(); void enviar({ acao: "configurar_freelance", usuario: integrante, ativo: freelanceAtivo, valor: Number(valorFreelance), pix }); }} className="grid gap-3 rounded-2xl bg-surface-container-low p-4 sm:grid-cols-2"><h3 className="font-semibold sm:col-span-2">Cadastro financeiro do integrante</h3><label className="text-sm sm:col-span-2">Pessoa<select className={campo} value={integrante} onChange={e => setIntegrante(e.target.value)} required><option value="">Escolha</option>{pessoas.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={freelanceAtivo} onChange={e => setFreelanceAtivo(e.target.checked)} />Freelancer</label><label className="text-sm">Valor por evento (R$)<input className={campo} type="number" step="0.01" min="0" value={valorFreelance} onChange={e => setValorFreelance(e.target.value)} required /></label><label className="text-sm sm:col-span-2">Chave Pix<input className={campo} value={pix} onChange={e => setPix(e.target.value)} maxLength={200} /></label><button disabled={ocupado || !integrante} className="rounded-xl bg-primary px-4 py-2 text-on-primary disabled:opacity-50 sm:col-span-2">Salvar cadastro</button></form>
      <form onSubmit={e => { e.preventDefault(); const f = faturas.find(item => `${item.cartao_id}|${item.competencia}` === faturaEscolhida); if (f) void enviar({ acao: "pagar_fatura", cartao: f.cartao_id, competencia: f.competencia, data: hojeBrasil(), valor: Number(valorFatura) }).then(ok => { if (ok) setValorFatura(""); }); }} className="grid content-start gap-3 rounded-2xl bg-surface-container-low p-4"><h3 className="font-semibold">Registrar pagamento de fatura</h3><label className="text-sm">Fatura<select className={campo} value={faturaEscolhida} onChange={e => { setFaturaEscolhida(e.target.value); const f = faturas.find(item => `${item.cartao_id}|${item.competencia}` === e.target.value); setValorFatura(f ? (Number(f.total) - Number(f.pago)).toFixed(2) : ""); }} required><option value="">Escolha</option>{faturas.filter(f => Number(f.total) > Number(f.pago)).map(f => <option key={`${f.cartao_id}|${f.competencia}`} value={`${f.cartao_id}|${f.competencia}`}>{f.nome} · {f.competencia.slice(0, 7)} · falta {formatBRL(Number(f.total) - Number(f.pago))}</option>)}</select></label><label className="text-sm">Valor pago (R$)<input className={campo} type="number" min="0.01" step="0.01" value={valorFatura} onChange={e => setValorFatura(e.target.value)} required /></label><button disabled={ocupado || !faturaEscolhida} className="rounded-xl bg-primary px-4 py-2 text-on-primary disabled:opacity-50">Registrar pagamento</button></form>
    </section>
    {erro && <p role="alert" className="rounded-xl bg-error-container p-3 text-on-error-container">{erro}</p>}
  </div>;
}
