import {chromium} from './.runtime/node_modules/playwright/index.mjs';
import {cookiesDeSessao} from './sessao.mjs';
import {execFileSync} from 'node:child_process';
import QRCode from 'qrcode';
const email=execFileSync('docker',['exec','supabase_db_Nicolas','psql','-U','postgres','-d','postgres','-Atc',"select email from usuario where papel='admin' limit 1"]).toString().trim();
const codigo='cecchin:saida:demo:cecchin-demonstracao-saida';await QRCode.toFile('skills/verificar-tela/capturas/qr-demonstracao.png',codigo,{width:640,margin:4});const imagem=await QRCode.toDataURL(codigo,{width:640,margin:4});
const browser=await chromium.launch({executablePath:'C:/Users/josh/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe',headless:true});
try{const context=await browser.newContext({viewport:{width:1440,height:900}});await context.addCookies(await cookiesDeSessao('http://localhost:3000',email,'mock'));const page=await context.newPage();const erros=[];page.on('pageerror',e=>erros.push(e.message));let escritas=0;page.on('request',r=>{if(r.url().includes('/api/operacao/embarque')&&r.method()==='POST')escritas++;});await page.goto('http://localhost:3000/operacional/minha-rota');await page.waitForTimeout(1500);const ordem=(await page.locator('aside nav').innerText()).toLocaleLowerCase('pt-BR');if(!(ordem.indexOf('equipe de campo')<ordem.indexOf('opera\u00e7\u00f5es & despacho')&&ordem.indexOf('opera\u00e7\u00f5es & despacho')<ordem.indexOf('administra\u00e7\u00e3o')))throw Error('Ordem sidebar incorreta');const gps=await page.getByRole('link',{name:'Iniciar Rota GPS',exact:true}).getAttribute('href');await page.screenshot({path:'skills/verificar-tela/capturas/rota-demonstracao.png',mask:[page.locator('header').first()]});await page.getByRole('button',{name:'Checklist e sa\u00edda',exact:true}).click();for(const checkbox of await page.locator('input[type=checkbox]').all())await checkbox.check();await page.getByRole('button',{name:'Mostrar QR para impress\u00e3o',exact:true}).click();await page.getByRole('img',{name:'QR de sa\u00edda do evento',exact:true}).waitFor();await page.getByRole('button',{name:/Liberar sa\u00edda/}).click();
await page.evaluate(async src=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=640;const img=new Image();img.src=src;await img.decode();canvas.getContext('2d').drawImage(img,0,0);window.__qrCanvas=canvas;setInterval(()=>canvas.getContext('2d').drawImage(img,0,0),100);Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>canvas.captureStream(10),configurable:true});},imagem);
await page.getByRole('button',{name:'Abrir c\u00e2mera',exact:true}).click();await page.getByRole('status').filter({hasText:'Sa\u00edda de demonstra\u00e7\u00e3o liberada'}).waitFor();console.log(JSON.stringify({sidebarOrdenada:true,gpsDirecoes:gps.includes('/maps/dir/'),qrCameraSimulada:true,nenhumaEscritaReal:escritas===0,erros}));}finally{await browser.close();}
