import {chromium} from './.runtime/node_modules/playwright/index.mjs';import {cookiesDeSessao} from './sessao.mjs';import {execFileSync} from 'node:child_process';
const email=execFileSync('docker',['exec','supabase_db_Nicolas','psql','-U','postgres','-d','postgres','-Atc',"select email from usuario where papel='admin' limit 1"]).toString().trim();const b=await chromium.launch({executablePath:'C:/Users/josh/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});try{const c=await b.newContext({viewport:{width:1920,height:1080}});await c.addCookies(await cookiesDeSessao('http://localhost:3000',email));await c.addCookies([{name:'cecchin_fonte',value:'mock',url:'http://localhost:3000'}]);const p=await c.newPage();const errors=[],writes=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().includes('/api/operacao/')&&['POST','PATCH','DELETE'].includes(r.method()))writes.push(r.method());});
await c.addCookies([{name:'cecchin_fonte',value:'real',url:'http://localhost:3000'}]);
const numero='5551000000000';
const msg=n=>({id:`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,direcao:n%2?'entrada':'saida',tipo:'text',conteudo:{texto:`Mensagem demonstrativa ${n}`},status:'lida',criado_em:new Date(Date.UTC(2026,8,15,10,0,n)).toISOString()});
let mensagens=Array.from({length:250},(_,i)=>msg(i+1));let pedidosAntigos=0;
await p.route('**/api/operacao/whatsapp?**',async route=>{const u=new URL(route.request().url());let resposta;
 if(u.searchParams.get('avisos'))resposta={ids:[],telefones:[],quantidade:0};
 else if(u.searchParams.get('telefone')){let itens=[...mensagens];const antes=u.searchParams.get('antes'),depois=u.searchParams.get('depois'),limite=Number(u.searchParams.get('limite')??50);if(antes){pedidosAntigos++;const [data,id]=antes.split('|');itens=itens.filter(m=>m.criado_em<data||(m.criado_em===data&&m.id<id));}if(depois){const [data,id]=depois.split('|');itens=itens.filter(m=>m.criado_em>data||(m.criado_em===data&&m.id>id));}itens.sort((a,b)=>a.criado_em.localeCompare(b.criado_em));if(!depois)itens.reverse();const lote=itens.slice(0,limite);resposta={total:mensagens.length,historicoOculto:false,assumida:false,modo:'automatico',fila:[],temMais:itens.length>limite,mensagens:depois?lote.reverse():lote};}
 else resposta={total:1,telefones:[numero],conversas:[{telefone:numero,modo:'automatico',atendente_id:null}],temMais:false};
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(resposta)});
});
await p.route('**/api/operacao/whatsapp',route=>route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'}));
await p.setViewportSize({width:1440,height:1000});await p.goto('http://localhost:3000/operacional/whatsapp');await p.waitForTimeout(1500);await p.getByRole('textbox',{name:'Número da conversa',exact:true}).fill(numero);await p.getByRole('button',{name:'Abrir conversa',exact:true}).click();const scroll=p.locator('[aria-label="Histórico da conversa"]');await scroll.waitFor();await p.waitForTimeout(600);
const fim=()=>scroll.evaluate(el=>el.scrollHeight-el.scrollTop-el.clientHeight);
if(await fim()>64)throw Error('Nao abriu no fim');if(await p.getByRole('navigation',{name:'Páginas de mensagens'}).count())throw Error('Paginador antigo');
await scroll.evaluate(el=>el.scrollTop=0);await p.waitForTimeout(900);if(await scroll.locator('[data-mensagem]').count()!==200)throw Error('Lote anterior');const ancora=await scroll.evaluate(el=>{const top=el.getBoundingClientRect().top;return Array.from(el.querySelectorAll('[data-mensagem]')).find(n=>n.getBoundingClientRect().bottom>top+1)?.getAttribute('data-mensagem');});if(!ancora?.endsWith('151'))throw Error('Ancora mudou ao carregar');await p.getByRole('button',{name:'Ir para mensagens recentes',exact:true}).waitFor();mensagens.push(msg(251));await p.waitForTimeout(11000);await p.getByRole('button',{name:'Ir para mensagens recentes: 1 novas mensagens',exact:true}).waitFor();const ancoraNova=await scroll.evaluate(el=>{const top=el.getBoundingClientRect().top;return Array.from(el.querySelectorAll('[data-mensagem]')).find(n=>n.getBoundingClientRect().bottom>top+1)?.getAttribute('data-mensagem');});if(ancoraNova!==ancora)throw Error('Nova mensagem moveu leitura');await p.screenshot({path:'skills/verificar-tela/capturas/whatsapp-historico-novas.png',mask:[p.locator('header')]});await p.getByRole('button',{name:/Ir para mensagens recentes/}).click();await p.waitForTimeout(900);if(await fim()>64)throw Error('Botao nao desceu');await scroll.evaluate(el=>el.scrollTop=0);await p.waitForTimeout(700);if(await scroll.locator('[data-mensagem]').count()!==251)throw Error('Fim historico');await p.setViewportSize({width:390,height:844});await p.waitForTimeout(500);await p.screenshot({path:'skills/verificar-tela/capturas/whatsapp-historico-mobile.png',mask:[p.locator('header')]});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow');console.log({inicioNoFim:true,ancoraPreservada:true,novasSinalizadas:true,retornoAoFim:true,pedidosAntigos,errors});}finally{await b.close()}
