import {chromium} from './.runtime/node_modules/playwright/index.mjs';
import {cookiesDeSessao} from './sessao.mjs';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
const db=s=>execFileSync('docker',['exec','supabase_db_Nicolas','psql','-U','postgres','-d','postgres','-At','-v','ON_ERROR_STOP=1','-c',s]).toString().trim();
const org=db("select organizacao_id from usuario where papel='admin' limit 1"), adminEmail=db("select email from usuario where papel='admin' limit 1");
const evento=randomUUID(),cliente=randomUUID(),users=[];let browser;
const api=process.env.SUPABASE_URL??'http://127.0.0.1:54321',headers={apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json'};
try{
 for(let i=0;i<3;i++){const email=`prova.montagem.${randomUUID()}@cecchin.test`;const r=await fetch(`${api}/auth/v1/admin/users`,{method:'POST',headers,body:JSON.stringify({email,email_confirm:true,user_metadata:{nome:i===2?'Cliente demonstracao':`Equipe demonstracao ${i+1}`}})});if(!r.ok)throw Error('Criacao de conta sintetica falhou');const u=await r.json();users.push({id:u.id,email});db(`update usuario set nome='${i===2?'Cliente demonstracao':`Equipe demonstracao ${i+1}`}',organizacao_id='${org}',papel='${i===2?'cliente':'staff'}' where id='${u.id}';update preferencia_notificacao set receber_email=false,receber_whatsapp=false,avisar_evento_novo=false,avisar_escala=false,avisar_disciplina=false where usuario_id='${u.id}';`);}
 db(`begin;insert into cliente(id,organizacao_id,nome,contato_bruto,usuario_id) values('${cliente}','${org}','Evento demonstracao','PROVA-MONTAGEM','${users[2].id}');insert into evento(id,organizacao_id,cliente_id,data_evento,horario,inteiros,meios,observacao,codigo_legado) values('${evento}','${org}','${cliente}',current_date,'00:00',30,5,'Garcom extra','PROVA-MONTAGEM');delete from notificacao where evento_id='${evento}';commit;`);
 browser=await chromium.launch({executablePath:'C:/Users/josh/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});const ctx=await browser.newContext({viewport:{width:1440,height:900}});await ctx.addCookies(await cookiesDeSessao('http://localhost:3000',adminEmail));const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.url().includes('/api/operacao/montagem-equipe')&&r.request().method()==='POST')console.log('salvar',r.status(),await r.text());});await page.goto(`http://localhost:3000/admin/montar-equipe?evento=${evento}`);await page.waitForTimeout(1800);console.log('tela carregada');await page.getByLabel('Equipe base',{exact:true}).fill('1');if(await page.getByLabel('Integrantes extras',{exact:true}).inputValue()!=='1')throw Error('Extra nas observacoes ignorado');await page.getByLabel('Buscar pessoa').fill('Equipe demonstracao');
 await page.getByRole('article').filter({hasText:'Equipe demonstracao 1'}).getByRole('button',{name:'Adicionar',exact:true}).click();
 await page.getByRole('article').filter({hasText:'Equipe demonstracao 2'}).getByRole('button',{name:'Adicionar',exact:true}).click();
 await page.getByRole('region',{name:'Equipe do evento',exact:true}).getByRole('button',{name:'Retirar',exact:true}).first().click();
 const handle=page.getByRole('button',{name:'Arrastar Equipe demonstracao 1',exact:true});await handle.scrollIntoViewIfNeeded();const h=await handle.boundingBox(),target=await page.getByRole('region',{name:'Equipe do evento',exact:true}).boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+12,h.y+12,{steps:3});await page.mouse.move(target.x+target.width/2,target.y+60,{steps:15});await page.mouse.up();if(await page.getByRole('region',{name:'Equipe do evento',exact:true}).getByRole('article').count()!==2)throw Error('Arrastar pessoa falhou');
 await page.getByRole('region',{name:'Equipe do evento',exact:true}).getByRole('button',{name:'Retirar',exact:true}).first().click();const bulk=page.getByRole('button',{name:'Arrastar equipe sugerida',exact:true});await bulk.scrollIntoViewIfNeeded();const bh=await bulk.boundingBox(),bt=await page.getByRole('region',{name:'Equipe do evento',exact:true}).boundingBox();await page.mouse.move(bh.x+bh.width/2,bh.y+bh.height/2);await page.mouse.down();await page.mouse.move(bh.x+12,bh.y+12,{steps:3});await page.mouse.move(bt.x+bt.width/2,bt.y+60,{steps:15});await page.mouse.up();if(await page.getByRole('region',{name:'Equipe do evento',exact:true}).getByRole('article').count()!==2)throw Error('Arrastar equipe falhou');
 console.log('pessoas selecionadas');await page.waitForTimeout(500);await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await page.getByRole('status').filter({hasText:'Rascunho salvo'}).waitFor();await page.reload();await page.waitForTimeout(1500);if(await page.getByRole('region',{name:'Equipe do evento',exact:true}).getByRole('article').count()!==2)throw Error('Rascunho nao persistiu');
 await page.getByRole('button',{name:'Confirmar equipe e convidar',exact:true}).click();await page.getByRole('button',{name:'Confirmar convites',exact:true}).click();await page.getByRole('status').filter({hasText:'Equipe confirmada'}).waitFor();if(db(`select count(*) from escala_evento where evento_id='${evento}' and status='convidado'`)!=='2')throw Error('Convites ausentes');
 await page.getByLabel('Buscar pessoa').fill('Equipe demonstracao');for(const[n,width,height]of[['desktop',1440,900],['tablet',834,1112],['mobile',390,844]]){await page.setViewportSize({width,height});await page.evaluate(()=>document.documentElement.setAttribute('data-tema','escuro'));await page.getByRole('region',{name:'Equipe do evento',exact:true}).scrollIntoViewIfNeeded();await page.waitForTimeout(300);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow '+n);await page.screenshot({path:`skills/verificar-tela/capturas/montagem-${n}.png`,mask:[page.locator('header').first()]});}
 console.log('convites e layout conferidos');db(`update escala_evento set status='aceito',respondido_em=now() where evento_id='${evento}';`);
 const cli=await browser.newContext({viewport:{width:390,height:844}});await cli.addCookies(await cookiesDeSessao('http://localhost:3000',users[2].email));const cp=await cli.newPage();cp.on('pageerror',e=>errors.push(e.message));await cp.goto(`http://localhost:3000/cliente/avaliar-evento?evento=${evento}`);await cp.waitForTimeout(1500);const denied=await cp.evaluate(async()=>({planner:(await fetch('/api/operacao/montagem-equipe')).status,other:(await fetch('/api/cliente/avaliar-evento?evento=00000000-0000-4000-8000-000000000000')).status}));if(denied.planner!==403||denied.other!==403)throw Error('Acesso indevido');await cp.getByRole('button',{name:'Nota do evento: 0 de 5',exact:true}).click();await cp.getByRole('button',{name:'Equipe demonstracao 1: 5 de 5',exact:true}).click();await cp.getByRole('button',{name:'Equipe demonstracao 2: 0 de 5',exact:true}).click();await cp.screenshot({path:'skills/verificar-tela/capturas/avaliacao-mobile.png',mask:[cp.locator('header').first()]});await cp.getByRole('button',{name:'Confirmar fim do atendimento e enviar notas',exact:true}).click();await cp.getByRole('status').filter({hasText:'Evento finalizado'}).waitFor();await cp.reload();await cp.getByRole('status').filter({hasText:'Nota do evento: 0/5'}).waitFor();if(db(`select count(*) from avaliacao_cliente_integrante where evento_id='${evento}'`)!=='2')throw Error('Notas individuais ausentes');if(db(`select count(*) from vw_eventos_montagem where id='${evento}'`)!=='0')throw Error('Evento finalizado continua na montagem');console.log(JSON.stringify({arrastarPessoa:true,arrastarEquipe:true,acessoRestrito:true,extraObservacao:true,rascunhoPersistente:true,convites:2,notaZero:true,notasIndividuais:true,finalizadoSaiDaMontagem:true,errors}));
}finally{if(browser)await browser.close();db(`begin;delete from avaliacao_cliente_integrante where evento_id='${evento}';delete from avaliacao_cliente_evento where evento_id='${evento}';delete from planejamento_equipe where evento_id='${evento}';delete from notificacao where evento_id='${evento}';delete from escala_evento where evento_id='${evento}';delete from evento_qr_saida where evento_id='${evento}';delete from evento where id='${evento}';delete from cliente where id='${cliente}';commit;`);for(const u of users)await fetch(`${api}/auth/v1/admin/users/${u.id}`,{method:'DELETE',headers});}
