import {chromium} from './.runtime/node_modules/playwright/index.mjs';
import {cookiesDeSessao} from './sessao.mjs';
import {execFileSync} from 'node:child_process';
const email=execFileSync('docker',['exec','supabase_db_Nicolas','psql','-U','postgres','-d','postgres','-Atc',"select email from usuario where papel='admin' limit 1"]).toString().trim();
const b=await chromium.launch({executablePath:'C:/Users/josh/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});
try { const c=await b.newContext({viewport:{width:1440,height:900}});await c.addCookies(await cookiesDeSessao('http://localhost:3000',email));const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const real=await c.request.get('http://localhost:3000/api/operacao/notificacoes?selecao=1');const resultadoReal=await real.json();if(real.status()!==200||!Array.isArray(resultadoReal.pessoas))throw Error('Selecao real falhou');const invalido=await c.request.patch('http://localhost:3000/api/operacao/notificacoes',{data:{escopo:'preferencias_lote',usuarios:[],alteracoes:{receber_email:true}}});const erroReal=await invalido.json();if(invalido.status()!==403||!erroReal.mensagem.includes('Selecione entre'))throw Error('RPC nao resolveu');console.log({selecaoReal:true,rpcRealValidada:true});
const todas=Array.from({length:240},(_,i)=>({id:`demo-${i}`,nome:`Pessoa demonstrativa ${String(i+1).padStart(3,'0')}`,email:'pessoa@example.invalid',telefone:null,papel:i%2?'staff':'gestao',receber_email:true,receber_whatsapp:false,avisar_evento_novo:true,avisar_escala:true,avisar_disciplina:true}));let lote;
await p.route('**/api/operacao/notificacoes?*',async route=>{const url=new URL(route.request().url());const pagina=Number(url.searchParams.get('pagina')||1);const busca=(url.searchParams.get('busca')||'').toLowerCase();const papel=url.searchParams.get('papel');const filtradas=todas.filter(p=>(!papel||p.papel===papel)&&(!busca||p.nome.toLowerCase().includes(busca)));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({total:filtradas.length,pessoas:url.searchParams.get('selecao')==='1'?filtradas:filtradas.slice((pagina-1)*12,pagina*12)})});});
await p.route('**/api/operacao/notificacoes',async route=>{if(route.request().method()!=='PATCH')return route.continue();lote=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,atualizados:lote.usuarios.length})});});
await p.goto('http://localhost:3000/admin/notificacoes');await p.waitForTimeout(1400);const nav=p.getByRole('navigation',{name:'P\u00e1ginas de destinat\u00e1rios'});await nav.getByText(/240 registros/).waitFor();await p.getByRole('checkbox',{name:'Selecionar esta p\u00e1gina',exact:true}).check();await nav.getByRole('spinbutton').fill('20');await nav.getByRole('button',{name:'Ir',exact:true}).click();await p.getByRole('article',{name:/Pessoa demonstrativa 240/}).waitFor();await p.getByRole('checkbox',{name:'Selecionar Pessoa demonstrativa 240',exact:true}).check();await p.getByText('13 selecionados em todas as p\u00e1ginas',{exact:true}).waitFor();await p.getByRole('combobox',{name:'Perfil dos destinat\u00e1rios'}).selectOption('staff');await nav.getByText(/120 registros/).waitFor();await p.getByText('13 selecionados em todas as p\u00e1ginas',{exact:true}).waitFor();await p.getByRole('button',{name:'Selecionar 120 dos filtros',exact:true}).click();await p.getByText('126 selecionados em todas as p\u00e1ginas',{exact:true}).waitFor();await p.getByRole('button',{name:'Editar selecionados',exact:true}).click();const editor=p.getByRole('region',{name:'Edi\u00e7\u00e3o em lote'});await editor.getByRole('combobox',{name:'WhatsApp',exact:true}).selectOption('ativar');await editor.getByRole('combobox',{name:'Novo evento',exact:true}).selectOption('desativar');for(const width of [1440,834,390]){await p.setViewportSize({width,height:1000});await p.evaluate(()=>document.documentElement.setAttribute('data-tema','escuro'));await p.waitForTimeout(400);await editor.scrollIntoViewIfNeeded();await p.screenshot({path:`skills/verificar-tela/capturas/regras-lote-${width}.png`,mask:[p.locator('header')]});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow');}await editor.getByRole('button',{name:'Aplicar em 126 pessoas'}).click();await p.getByText('0 selecionados em todas as p\u00e1ginas',{exact:true}).waitFor();if(lote.usuarios.length!==126||Object.keys(lote.alteracoes).length!==2||lote.alteracoes.receber_whatsapp!==true||lote.alteracoes.avisar_evento_novo!==false)throw Error('Lote incorreto');console.log({selecaoEntrePaginas:true,filtroPreservou:true,lote126:true,camposPreservados:true,errors});await p.setViewportSize({width:1440,height:1000});await p.waitForTimeout(500);await p.getByRole('article').first().scrollIntoViewIfNeeded();await p.screenshot({path:'skills/verificar-tela/capturas/regras-grupos.png',mask:[p.locator('header')]});
}finally{await b.close()}
