"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Search,MapPin} from "lucide-react";
import {pessoasDemo} from "../../lib/demo-operacao";
import {TituloNoHeader} from "../layouts/TituloNoHeader";
import {Paginacao} from "../painel/Paginacao";
import {AvatarPessoa} from "./AvatarPessoa";
import {EstrelasNota} from "./EstrelasNota";
import {PerfilIntegrante} from "./PerfilIntegrante";
import {TransporteEquipe} from "./TransporteEquipe";
import type {PessoaEquipe,PerfilEquipe} from "./tipos";

export function EquipeOperacao({demo}:{demo:boolean}){
 const [pendentes,setPendentes]=useState<Array<{id:string;nome:string;funcao_origem:string|null;telefone_provisorio:boolean;usuario_id:string|null;apto_teste:boolean;forno_teste:boolean;garcom_teste:boolean}>>([]);
 useEffect(()=>{if(demo)return;const controller=new AbortController();void fetch('/api/operacao/pre-cadastros',{signal:controller.signal,cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(!controller.signal.aborted)setPendentes((d.cadastros??[]).filter((c:{usuario_id:string|null})=>!c.usuario_id));}).catch(()=>{});return()=>controller.abort();},[demo]);
 const [pessoas,setPessoas]=useState<PessoaEquipe[]>([]),[pagina,setPagina]=useState(0),[busca,setBusca]=useState(''),[filtro,setFiltro]=useState(''),[total,setTotal]=useState(0),[selecionada,setSelecionada]=useState<PessoaEquipe|null>(null),[erro,setErro]=useState(''),[carregando,setCarregando]=useState(true);
 useEffect(()=>{const t=setTimeout(()=>{setFiltro(busca.trim());setPagina(0);},300);return()=>clearTimeout(t);},[busca]);
 useEffect(()=>{const controller=new AbortController();setErro('');setCarregando(true);if(demo){let perfis:Record<string,PerfilEquipe>={};try{perfis=JSON.parse(localStorage.getItem('cecchin:demo:perfis')??'{}');}catch{}const lista=pessoasDemo.map((p,i)=>({...p,foto_url:i%4===0?null:p.foto_url,perfil:perfis[p.id]??p.perfil})).filter(p=>p.nome.toLocaleLowerCase('pt-BR').includes(filtro.toLocaleLowerCase('pt-BR')));setTotal(lista.length);setPessoas(lista.slice(pagina*24,pagina*24+24));setCarregando(false);return;}void fetch(`/api/operacao/montagem-equipe?equipe=1&pagina=${pagina}&busca=${encodeURIComponent(filtro)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.mensagem);if(!controller.signal.aborted){setPessoas(d.pessoas);setTotal(d.total);}}).catch(e=>{if(!controller.signal.aborted)setErro(e.message);}).finally(()=>{if(!controller.signal.aborted)setCarregando(false);});return()=>controller.abort();},[demo,pagina,filtro]);
 async function salvar(id:string,perfil:PerfilEquipe){if((perfil.latitude===null)!==(perfil.longitude===null))throw Error('Informe latitude e longitude juntas.');if(demo){let perfis={};try{perfis=JSON.parse(localStorage.getItem('cecchin:demo:perfis')??'{}');}catch{}localStorage.setItem('cecchin:demo:perfis',JSON.stringify({...perfis,[id]:perfil}));}else{const r=await fetch('/api/operacao/montagem-equipe',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({acao:'perfil',usuario:id,perfil})});const d=await r.json();if(!r.ok)throw Error(d.mensagem);}setPessoas(a=>a.map(p=>p.id===id?{...p,perfil}:p));setSelecionada(a=>a?.id===id?{...a,perfil}:a);}
 return <div className="space-y-4"><TituloNoHeader>Equipe de operação</TituloNoHeader><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl bg-surface-container px-3 py-2"><Search size={17}/><input aria-label="Buscar integrante" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar integrante por nome" className="min-w-0 flex-1 bg-transparent outline-none"/></label><span className="text-xs text-on-surface-variant">{total} integrantes{!demo&&pendentes.length>0?` \u00b7 ${pendentes.length} aguardando ativação`:""}{demo?' · Desenho':''}</span>{!demo&&<Link href="/admin/operacao?aba=vinculos" className="rounded-xl bg-surface-container px-3 py-2 text-sm">Vínculos da agenda</Link>}</div>
 {erro&&<p role="alert" className="text-sm text-error">{erro}</p>}{carregando&&<p role="status" className="text-sm">Carregando integrantes…</p>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{pessoas.map(p=><article key={p.id} onContextMenu={e=>{e.preventDefault();setSelecionada(p);}} className="flex min-w-0 flex-col rounded-2xl border border-on-surface/10 bg-surface-container-low p-4 shadow-sm"><button onClick={()=>setSelecionada(p)} className="flex cursor-pointer items-center gap-3 text-left"><AvatarPessoa id={p.id} foto={p.foto_url} className="h-16 w-16"/><span className="min-w-0"><strong className="block break-words">{p.nome}</strong>{p.teste_operacional&&<span className="mt-1 block text-xs text-primary">Teste WhatsApp - checkout R$ 1,00</span>}<span className="text-xs text-primary">{p.perfil?.forno?(p.perfil.garcom?'Forno + atendimento':'Forno / liderança'):p.perfil?.garcom?'Atendimento':'Funções não cadastradas'}</span></span></button><p className="mt-3 text-xs text-on-surface-variant">{p.telefone??'Telefone não informado'}</p><div className="my-3 flex flex-wrap items-center gap-2 text-tertiary" aria-label={p.nota===null?'Sem avaliações':`Nota ${Number(p.nota).toFixed(1)} de 5`}><EstrelasNota nota={p.nota}/><span className="text-xs text-on-surface">{p.nota===null?'Sem nota':Number(p.nota).toFixed(1)} · {p.avaliacoes} avaliações</span></div><TransporteEquipe perfil={p.perfil}/><p className="my-3 flex gap-1.5 text-xs text-on-surface-variant"><MapPin size={14} className="shrink-0"/>{[p.perfil?.bairro,p.perfil?.cidade].filter(Boolean).join(' · ')||'Localização não cadastrada'}</p>{p.bloqueado&&<span className="mb-2 text-xs text-error">{p.teste_operacional?"Somente teste; fora de escalas reais":"Bloqueado para escala"}</span>}<button onClick={()=>setSelecionada(p)} className="mt-auto w-full cursor-pointer rounded-xl bg-surface-container px-3 py-2 text-sm">Perfil e mapa</button></article>)}</div>
 {!carregando&&!erro&&!pessoas.length&&<p className="text-sm text-on-surface-variant">Nenhum integrante encontrado.</p>}{!demo&&pendentes.length>0&&<section className="space-y-3 rounded-2xl bg-surface-container-low p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold">{pendentes.length} pré-cadastros aguardando ativação</h2><p className="text-sm text-on-surface-variant">Contam apenas no checkout real de teste de R$ 1,00; eventos normais ainda exigem equipe confirmada.</p></div><Link href="/admin/operacao?aba=vinculos" className="rounded-xl bg-surface-container px-3 py-2 text-sm">Gerenciar contatos</Link></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{pendentes.filter(p=>p.nome.toLocaleLowerCase('pt-BR').includes(filtro.toLocaleLowerCase('pt-BR'))).map(p=><div key={p.id} className="rounded-xl bg-surface-container-lowest p-3"><strong className="block text-sm">{p.nome}</strong><span className="block text-xs text-on-surface-variant">{p.funcao_origem||'Função de origem não informada'} · {p.telefone_provisorio?'WhatsApp provisório':'Aguardando confirmação do titular'}</span>{p.apto_teste&&<span className="mt-2 inline-block rounded-lg bg-primary/10 px-2 py-1 text-xs text-primary">Cenário R$ 1,00: {p.forno_teste?'forno/liderança':p.garcom_teste?'atendimento':'sem função'}</span>}</div>)}</div><p className="text-xs text-on-surface-variant">Para eventos normais: WhatsApp real, acesso confirmado, função de forno/atendimento e disponibilidade semanal.</p></section>}<Paginacao pagina={pagina+1} total={total} porPagina={24} onPagina={p=>setPagina(p-1)} rotulo="Páginas de integrantes"/>{selecionada&&<PerfilIntegrante key={selecionada.id} pessoa={selecionada} demo={demo} salvar={salvar} fechar={()=>setSelecionada(null)}/>}
 </div>;
}
