"use client";
import {useEffect,useRef,type ReactNode} from "react";
import {createPortal} from "react-dom";
import {X} from "lucide-react";
export function JanelaEquipe({titulo,fechar,children,ampla=false,grande=false}:{titulo:string;fechar:()=>void;children:ReactNode;ampla?:boolean;grande?:boolean}){
 const ref=useRef<HTMLDivElement>(null),sair=useRef(fechar);sair.current=fechar;
 useEffect(()=>{const anterior=document.activeElement as HTMLElement|null;ref.current?.focus();const key=(e:KeyboardEvent)=>{const modais=document.querySelectorAll('[aria-modal="true"]');if(modais[modais.length-1]!==ref.current)return;if(e.key==="Escape"){e.stopImmediatePropagation();sair.current();}if(e.key==="Tab"){const itens=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]');if(!itens?.length)return;const primeiro=itens[0],ultimo=itens[itens.length-1];if(e.shiftKey&&(document.activeElement===primeiro||document.activeElement===ref.current)){e.preventDefault();ultimo.focus();}else if(!e.shiftKey&&document.activeElement===ultimo){e.preventDefault();primeiro.focus();}}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);anterior?.focus();};},[]);
 return createPortal(<div className={`fixed inset-0 ${ampla?'z-[70]':'z-[120]'} flex items-center justify-center bg-inverse-surface/45 p-3`} onPointerDown={e=>{if(e.target===e.currentTarget)fechar();}}><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={titulo} className={`flex max-h-[94dvh] w-full ${ampla?'max-w-[1500px]':grande?'max-w-6xl':'max-w-xl'} flex-col overflow-hidden rounded-2xl border border-on-surface/15 bg-surface text-on-surface shadow-2xl outline-none`}><div className="flex items-center justify-between gap-3 border-b border-on-surface/10 px-4 py-3"><h2 className="font-semibold">{titulo}</h2><button aria-label={`Fechar ${titulo}`} onClick={fechar} className="cursor-pointer rounded-lg p-2 hover:bg-surface-container"><X size={18}/></button></div>{children}</div></div>,document.body);
}
