"use client";
import { TituloNoHeader } from "@/src/components/layouts/TituloNoHeader";

import {useEffect,useMemo,useState,type ReactNode} from "react";
import {useSearchParams} from "next/navigation";
import {DndContext,PointerSensor,KeyboardSensor,useSensor,useSensors,useDraggable,useDroppable,type DragEndEvent} from "@dnd-kit/core";
import {GripVertical,Star,UserRound} from "lucide-react";
type Pessoa={id:string;nome:string;telefone:string|null;foto_url:string|null;nota:number|null;avaliacoes:number;bloqueado:boolean};
type Evento={id:string;cliente_nome:string|null;data_evento:string;inteiros:number|null;meios:number|null;descricao_extra?:string|null;observacao?:string|null};
type Dados={evento:Evento;pessoas:Pessoa[];plano:{quantidade_base:number;extras:number;pessoas:string[]}|null;escala:{usuario_id:string}[];regra:{convidados_por_integrante:number|null;minimo:number}|null};
function extrasDoTexto(texto:string){const t=texto.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(/sem |nao /.test(t))return 0;const n=t.match(/(\d+)\s+garco(?:m|ns|es)\s+extras?/);if(n)return Math.min(50,Number(n[1]));return /garcom extra/.test(t)?1:0;}
function Area({id,titulo,children}:{id:string;titulo:string;children:ReactNode}){const {setNodeRef,isOver}=useDroppable({id});return <section ref={setNodeRef} aria-label={titulo} className={`min-w-0 rounded-2xl border p-4 ${isOver?"border-primary bg-primary/10":"border-on-surface/15 bg-surface-container-low"}`}><h2 className="mb-4 text-lg font-bold">{titulo}</h2>{children}</section>;}
function Cartao({p,selecionado,alterar,disabled}:{p:Pessoa;selecionado:boolean;alterar:()=>void;disabled:boolean}){const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:p.id,disabled:disabled||(p.bloqueado&&!selecionado)});return <article ref={setNodeRef} style={{transform:transform?`translate3d(${transform.x}px,${transform.y}px,0)`:undefined,zIndex:isDragging?50:undefined,position:"relative"}} className={`rounded-xl border border-on-surface/10 bg-surface-container-lowest p-3 shadow-sm ${p.bloqueado?"opacity-50":""}`}>
 <div className="flex items-start justify-between gap-2">{p.foto_url&&/^https?:\/\//.test(p.foto_url)?<img src={p.foto_url} alt="" className="h-12 w-12 rounded-full object-cover"/>:<span className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary"><UserRound/></span>}<button {...attributes} {...listeners} aria-label={`Arrastar ${p.nome}`} className="touch-none rounded-lg p-2 text-on-surface-variant"><GripVertical size={18}/></button></div>
 <h3 className="mt-2 break-words font-semibold">{p.nome}</h3><p className="break-all text-xs text-on-surface-variant">{p.telefone??"Telefone não informado"}</p><div className="mt-2 flex items-center gap-1 text-amber-600 dark:text-amber-300" aria-label={p.nota===null?"Sem avaliação":`Nota ${Number(p.nota).toFixed(1)} de 5`}>{[1,2,3,4,5].map(i=><Star key={i} size={16} fill={p.nota!==null&&i<=Math.round(Number(p.nota))?"currentColor":"none"}/>)}<span className="text-xs text-on-surface">{p.nota===null?"—":Number(p.nota).toFixed(1)}</span></div><p className="mt-1 text-xs text-on-surface-variant">{p.avaliacoes} avaliações{p.bloqueado?" · Bloqueado":""}</p><button disabled={disabled||(p.bloqueado&&!selecionado)} onClick={alterar} className="mt-3 w-full rounded-lg bg-surface-container px-2 py-2 text-sm disabled:opacity-40">{selecionado?"Retirar":"Adicionar"}</button></article>;}
function Sugestao({nomes,aplicar,disabled}:{nomes:string[];aplicar:()=>void;disabled:boolean}){const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:"sugestao",disabled});return <div ref={setNodeRef} style={{transform:transform?`translate3d(${transform.x}px,${transform.y}px,0)`:undefined,position:"relative",zIndex:isDragging?50:undefined}} className="mb-4 rounded-xl border border-primary/30 bg-primary/5 p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-bold">Equipe sugerida</h3><button {...attributes} {...listeners} aria-label="Arrastar equipe sugerida" className="touch-none rounded-lg p-2"><GripVertical/></button></div><p className="my-2 text-sm">{nomes.length?nomes.join(", "):"Defina o tamanho da equipe para gerar a sugestão."}</p><button disabled={disabled||!nomes.length} onClick={aplicar} className="rounded-lg bg-primary px-4 py-2 text-on-primary disabled:opacity-40">Usar equipe sugerida</button></div>;}
export function MontagemEquipe(){
 const params=useSearchParams();const [eventos,setEventos]=useState<Evento[]>([]),[evento,setEvento]=useState(params.get("evento")??""),[dados,setDados]=useState<Dados|null>(null),[selecionados,setSelecionados]=useState<string[]>([]),[base,setBase]=useState(""),[extras,setExtras]=useState(0),[busca,setBusca]=useState(""),[erro,setErro]=useState(""),[aviso,setAviso]=useState(""),[ocupado,setOcupado]=useState(false),[confirmar,setConfirmar]=useState(false);
 const [proporcao,setProporcao]=useState(""),[minimo,setMinimo]=useState(1);
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}),useSensor(KeyboardSensor));
 useEffect(()=>{const c=new AbortController();fetch("/api/operacao/montagem-equipe",{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.mensagem);setEventos(d.eventos);setEvento(atual=>atual||d.eventos[0]?.id||"");}).catch(e=>{if(!c.signal.aborted)setErro(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(!evento)return;const c=new AbortController();setDados(null);setErro("");setAviso("");setConfirmar(false);fetch(`/api/operacao/montagem-equipe?evento=${evento}`,{signal:c.signal,cache:"no-store"}).then(async r=>{const d:Dados=await r.json();if(!r.ok)throw Error((d as unknown as {mensagem:string}).mensagem);setDados(d);setProporcao(String(d.regra?.convidados_por_integrante??""));setMinimo(d.regra?.minimo??1);const quantidade=(d.evento.inteiros??0)+(d.evento.meios??0);const calculado=d.regra?.convidados_por_integrante?Math.max(d.regra.minimo,Math.ceil(quantidade/d.regra.convidados_por_integrante)):null;setBase(String(d.plano?.quantidade_base??calculado??(d.escala.length||"")));setExtras(d.plano?.extras??Math.max(extrasDoTexto(d.evento.descricao_extra??""),extrasDoTexto(d.evento.observacao??"")));setSelecionados(d.plano?.pessoas??d.escala.map(p=>p.usuario_id));}).catch(e=>{if(!c.signal.aborted)setErro(e.message);});return()=>c.abort();},[evento]);
 const quantidadeValida=Number.isInteger(Number(base))&&Number(base)>=1&&Number(base)<=50&&Number.isInteger(extras)&&extras>=0&&extras<=50;const vagas=quantidadeValida?Number(base)+extras:0;const ordenadas=useMemo(()=>[...(dados?.pessoas??[])].sort((a,b)=>(a.bloqueado?1:0)-(b.bloqueado?1:0)||(b.nota===null?-1:Number(b.nota))-(a.nota===null?-1:Number(a.nota))||b.avaliacoes-a.avaliacoes||a.nome.localeCompare(b.nome)),[dados]);
 const sugeridas=quantidadeValida?ordenadas.filter(p=>!p.bloqueado).slice(0,vagas):[];
 function adicionar(id:string){if(ocupado||!quantidadeValida)return;if(selecionados.length>=vagas){setErro("Todas as vagas estão preenchidas. Retire alguém ou aumente o tamanho.");return;}setSelecionados(p=>p.includes(id)?p:[...p,id]);setConfirmar(false);setAviso("");}
 function aplicar(){setSelecionados(sugeridas.map(p=>p.id));setConfirmar(false);setAviso("");}
 function soltar(e:DragEndEvent){if(e.over?.id==="equipe"){if(e.active.id==="sugestao")aplicar();else adicionar(String(e.active.id));}else if(e.over?.id==="pessoas"){setSelecionados(p=>p.filter(id=>id!==e.active.id));setConfirmar(false);setAviso("");}}
 async function salvarRegra(){setOcupado(true);setErro("");try{const r=await fetch("/api/operacao/montagem-equipe",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({convidados:Number(proporcao),minimo})});const d=await r.json();if(!r.ok)throw Error(d.mensagem);setDados(a=>a?{...a,regra:{convidados_por_integrante:Number(proporcao),minimo}}:a);setBase(String(Math.max(minimo,Math.ceil(((dados?.evento.inteiros??0)+(dados?.evento.meios??0))/Number(proporcao)))));setConfirmar(false);setAviso("Regra salva. Confira as vagas antes de confirmar a equipe.");}catch(e){setErro(e instanceof Error?e.message:"Falha ao salvar regra");}finally{setOcupado(false);}}
 async function salvar(enviar:boolean){setOcupado(true);setErro("");try{const r=await fetch("/api/operacao/montagem-equipe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({evento,base:Number(base),extras,pessoas:selecionados,confirmar:enviar})});const d=await r.json();if(!r.ok)throw Error(d.mensagem);setAviso(enviar?"Equipe confirmada. Novos integrantes foram convidados.":"Rascunho salvo.");setConfirmar(false);}catch(e){setErro(e instanceof Error?e.message:"Falha ao salvar");}finally{setOcupado(false);}}
 return <div className="mx-auto max-w-7xl space-y-5 pb-20"><header><TituloNoHeader className="text-2xl font-bold">Montar equipe do evento</TituloNoHeader><p className="mt-1 text-on-surface-variant">Escolha a sugestão por notas ou monte sua equipe livremente.</p></header><label className="block text-sm">Evento confirmado<select value={evento} disabled={ocupado} onChange={e=>setEvento(e.target.value)} className="mt-1 block w-full rounded-xl border border-on-surface/20 bg-surface-container p-3 text-on-surface">{eventos.map(e=><option key={e.id} value={e.id}>{e.data_evento} · {e.cliente_nome??"Evento"} · {(e.inteiros??0)+(e.meios??0)} pessoas</option>)}</select></label>
 {erro&&<p role="alert" className="rounded-xl bg-error/10 p-3 text-error">{erro}</p>}{aviso&&<p role="status" className="rounded-xl bg-primary/10 p-3">{aviso}</p>}
 {!dados?<p role="status">{eventos.length?"Carregando pessoas e notas...":"Nenhum evento carregado."}</p>:<><section className="flex flex-wrap items-end gap-4 rounded-xl bg-surface-container-low p-4"><label>Equipe base<input type="number" min={1} max={50} value={base} disabled={ocupado} onChange={e=>{setBase(e.target.value);setConfirmar(false);}} className="mt-1 block w-28 rounded-lg bg-surface p-2"/></label><label>Integrantes extras<input type="number" min={0} max={50} value={extras} disabled={ocupado} onChange={e=>{setExtras(Number(e.target.value));setConfirmar(false);}} className="mt-1 block w-28 rounded-lg bg-surface p-2"/></label><span className="pb-2 font-semibold">{selecionados.length}/{vagas||0} vagas preenchidas</span>{!dados.regra?.convidados_por_integrante&&<p className="basis-full text-sm text-on-surface-variant">A proporção de convidados por integrante ainda não foi definida. Informe a equipe base para este evento.</p>}{(dados.evento.descricao_extra||dados.evento.observacao)&&<p className="basis-full text-sm">Pedido registrado: {[dados.evento.descricao_extra,dados.evento.observacao].filter(Boolean).join(" / ")}. Confira a quantidade de integrantes extras.</p>}</section>
 <details className="rounded-xl bg-surface-container-low p-4"><summary className="cursor-pointer font-semibold">Regra de dimensionamento da organização</summary><p className="my-3 text-sm">A quantidade base será o total de convidados dividido por esta proporção, arredondado para cima, respeitando o mínimo. Integrantes extras são somados depois.</p><div className="flex flex-wrap items-end gap-3"><label>Convidados por integrante<input type="number" min={1} value={proporcao} onChange={e=>setProporcao(e.target.value)} className="mt-1 block w-32 rounded-lg bg-surface p-2"/></label><label>Mínimo de integrantes<input type="number" min={1} max={50} value={minimo} onChange={e=>setMinimo(Number(e.target.value))} className="mt-1 block w-32 rounded-lg bg-surface p-2"/></label><button disabled={ocupado||!proporcao} onClick={salvarRegra} className="rounded-lg bg-surface-container px-4 py-2">Salvar regra</button></div></details>
 <DndContext sensors={sensors} onDragEnd={soltar}><Sugestao nomes={sugeridas.map(p=>p.nome)} aplicar={aplicar} disabled={ocupado||!quantidadeValida}/><div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"><Area id="equipe" titulo="Equipe do evento"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{selecionados.map(id=>{const p=dados.pessoas.find(p=>p.id===id)??{id,nome:"Integrante indisponível",telefone:null,foto_url:null,nota:null,avaliacoes:0,bloqueado:true};return p?<Cartao key={id} p={p} selecionado disabled={ocupado} alterar={()=>{setSelecionados(s=>s.filter(i=>i!==id));setConfirmar(false);}}/>:null;})}{Array.from({length:Math.max(0,Math.min(100,vagas-selecionados.length))},(_,i)=><div key={`vaga-${i}`} className="flex min-h-44 items-center justify-center rounded-xl border-2 border-dashed border-on-surface/20 p-4 text-center text-sm text-on-surface-variant">Arraste uma pessoa para esta equipe</div>)}</div></Area><Area id="pessoas" titulo="Pessoas · maiores notas primeiro"><input aria-label="Buscar pessoa" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar nome ou telefone" className="mb-3 w-full rounded-lg bg-surface p-3"/><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{ordenadas.filter(p=>!selecionados.includes(p.id)&&`${p.nome} ${p.telefone??""}`.toLowerCase().includes(busca.toLowerCase())).map(p=><Cartao key={p.id} p={p} selecionado={false} disabled={ocupado||!quantidadeValida} alterar={()=>adicionar(p.id)}/>)}</div></Area></div></DndContext>
 <footer className="flex flex-wrap gap-3"><button disabled={ocupado||!quantidadeValida} onClick={()=>void salvar(false)} className="rounded-xl bg-surface-container px-5 py-3 disabled:opacity-40">Salvar rascunho</button><button disabled={ocupado||!quantidadeValida||selecionados.length!==vagas} onClick={()=>setConfirmar(true)} className="rounded-xl bg-primary px-5 py-3 text-on-primary disabled:opacity-40">Confirmar equipe e convidar</button></footer>{confirmar&&<section className="rounded-xl border border-primary/30 bg-surface-container-lowest p-4"><p>Confirmar {selecionados.length} pessoas? Novos integrantes receberão convites nos canais configurados. Pessoas retiradas terão a escala cancelada.</p><div className="mt-3 flex gap-3"><button disabled={ocupado} onClick={()=>setConfirmar(false)} className="rounded-lg bg-surface-container px-4 py-2">Voltar</button><button disabled={ocupado} onClick={()=>void salvar(true)} className="rounded-lg bg-primary px-4 py-2 text-on-primary">{ocupado?"Confirmando...":"Confirmar convites"}</button></div></section>}</>}
 </div>;
}
