"use client";
import {useState} from "react";
import {ChefHat,MapPin,Star,UserRound,Utensils} from "lucide-react";
import {AvatarPessoa} from "./AvatarPessoa";
import {MapaEquipe} from "./MapaEquipe";
import {TransporteEquipe,VEICULOS,MEIOS_TRANSPORTE} from "./TransporteEquipe";
import {JanelaEquipe} from "./JanelaEquipe";
import type {PessoaEquipe,PerfilEquipe,EventoEquipe} from "./tipos";
const vazio:PerfilEquipe={garcom:false,forno:false,endereco:null,bairro:null,cidade:null,latitude:null,longitude:null,apresentacao:null,transporte:null};
export function PerfilIntegrante({pessoa,fechar,salvar,demo,evento,aoLocalizarEvento}:{pessoa:PessoaEquipe;fechar:()=>void;salvar:(id:string,perfil:PerfilEquipe)=>Promise<void>;demo:boolean;evento?:EventoEquipe;aoLocalizarEvento?:(ponto:{latitude:number;longitude:number})=>void}){
 const [perfil,setPerfil]=useState<PerfilEquipe>(pessoa.perfil??vazio),[editando,setEditando]=useState(false),[ocupado,setOcupado]=useState(false),[mensagem,setMensagem]=useState(''),[locais,setLocais]=useState<Array<{endereco:string;lat:number;lng:number}>>([]);
 const campo=(nome:keyof PerfilEquipe,valor:unknown)=>setPerfil(p=>({...p,[nome]:valor}));
 async function buscar(){setOcupado(true);setMensagem('');try{const q=[perfil.endereco,perfil.bairro,perfil.cidade].filter(Boolean).join(', ');const r=await fetch(`/api/mapa/buscar?q=${encodeURIComponent(q)}`);const d=await r.json();if(!r.ok)throw Error(d.mensagem);setLocais(d.locais??[]);if(!d.locais?.length)setMensagem('Nenhum endereço encontrado. Confira os campos.');}catch(e){setMensagem(e instanceof Error?e.message:'Falha na busca');}finally{setOcupado(false);}}
 return <JanelaEquipe grande titulo="Perfil do integrante" fechar={fechar}><div className="grid min-h-0 min-w-0 grid-cols-1 overflow-y-auto lg:grid-cols-[minmax(300px,2fr)_minmax(0,3fr)]"><div className="min-w-0 p-4"><div className="flex min-w-0 items-center gap-4"><AvatarPessoa id={pessoa.id} foto={pessoa.foto_url} className="h-20 w-20 shrink-0"/><div className="min-w-0 flex-1"><h3 className="break-words text-xl font-bold [overflow-wrap:anywhere]">{pessoa.nome}</h3><p className="text-sm text-on-surface-variant">{pessoa.telefone??'Telefone não informado'}</p><p className="mt-1 flex items-center gap-1 text-sm"><Star size={15} fill="currentColor" className="text-tertiary"/>{pessoa.nota===null?'Sem avaliações':`${Number(pessoa.nota).toFixed(1)} · ${pessoa.avaliacoes} avaliações`}</p></div></div>
 {demo&&<p className="mt-3 text-xs text-primary">Perfil e localização demonstrativos.</p>}
 <div className="my-4 flex flex-wrap gap-2">{perfil.forno&&<span className="flex items-center gap-1 rounded-full bg-primary/10 px-3 py-1 text-xs text-primary"><ChefHat size={14}/>Forno · pode liderar</span>}{perfil.garcom&&<span className="flex items-center gap-1 rounded-full bg-tertiary/10 px-3 py-1 text-xs"><Utensils size={14}/>Garçom / atendimento</span>}{!perfil.forno&&!perfil.garcom&&<span className="text-sm text-on-surface-variant">Funções ainda não cadastradas</span>}{pessoa.bloqueado&&<span className="text-sm text-error">Bloqueado para escala</span>}</div>
 {!editando?<><p className="text-sm">{perfil.apresentacao||'Sem apresentação cadastrada.'}</p><p className="mt-4 flex gap-2 text-sm"><MapPin size={17} className="shrink-0"/>{[perfil.endereco,perfil.bairro,perfil.cidade].filter(Boolean).join(', ')||'Endereço não cadastrado'}</p><div className="mt-3"><TransporteEquipe perfil={perfil}/></div><p className="mt-2 text-sm text-on-surface-variant">Observações: {perfil.transporte||'Não informado'}</p><p className="mt-2 text-xs text-on-surface-variant">{perfil.latitude!==null&&perfil.longitude!==null?'Localização disponível para calcular casa → QG.':'Cadastre a localização para calcular o trajeto até o QG.'}</p><button onClick={()=>setEditando(true)} className="mt-5 cursor-pointer rounded-xl bg-primary px-4 py-2 text-sm text-on-primary">Editar perfil operacional</button></>:<form className="min-w-0 space-y-3" onSubmit={async e=>{e.preventDefault();setOcupado(true);setMensagem('');try{await salvar(pessoa.id,perfil);setEditando(false);setMensagem('Perfil salvo.');}catch(e){setMensagem(e instanceof Error?e.message:'Não foi possível salvar');}finally{setOcupado(false);}}}>
 <fieldset disabled={ocupado} className="min-w-0 space-y-3"><legend className="mb-2 text-sm font-semibold">Habilidades</legend><div className="flex flex-wrap gap-4"><label className="flex gap-2 text-sm"><input type="checkbox" checked={perfil.forno} onChange={e=>campo('forno',e.target.checked)}/>Forno / liderança</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={perfil.garcom} onChange={e=>campo('garcom',e.target.checked)}/>Garçom / atendimento</label></div>
 <div className="rounded-xl border border-tertiary/25 bg-tertiary/5 p-3"><p className="mb-2 text-xs font-semibold">Como a pessoa se desloca</p><div className="flex flex-wrap gap-2">{MEIOS_TRANSPORTE.map(({valor,nome,Icone})=><label key={valor} className="flex cursor-pointer items-center gap-2 rounded-lg bg-surface-container p-2 text-xs"><input type="checkbox" checked={perfil.meios_transporte?.includes(valor)??false} onChange={e=>campo('meios_transporte',e.target.checked?[...(perfil.meios_transporte??[]),valor]:(perfil.meios_transporte??[]).filter(v=>v!==valor))}/><Icone size={16}/>{nome}</label>)}</div></div>
 <div className="space-y-2"><p className="text-xs font-semibold">Veículos próprios da pessoa</p><div className="flex flex-wrap gap-2">{VEICULOS.map(({valor,nome,Icone})=><label key={valor} className="flex cursor-pointer items-center gap-2 rounded-lg border border-on-surface/15 p-2 text-xs"><input type="checkbox" checked={perfil.veiculos?.includes(valor)??false} onChange={e=>campo('veiculos',e.target.checked?[...(perfil.veiculos??[]),valor]:(perfil.veiculos??[]).filter(v=>v!==valor))}/><Icone size={16}/>{nome}</label>)}</div><p className="text-xs font-semibold">Categorias da CNH</p><div className="flex flex-wrap gap-2">{['A','B','C','D','E'].map(cat=><label key={cat} className="flex cursor-pointer items-center gap-1 rounded-lg bg-surface-container p-2 text-xs"><input type="checkbox" checked={perfil.cnh_categorias?.includes(cat)??false} onChange={e=>campo('cnh_categorias',e.target.checked?[...(perfil.cnh_categorias??[]),cat]:(perfil.cnh_categorias??[]).filter(v=>v!==cat))}/>{cat}</label>)}</div></div>
 {(['endereco','bairro','cidade','transporte'] as const).map((nome,i)=><label key={nome} className="block text-xs">{['Endereço residencial','Bairro','Cidade','Observações de deslocamento'][i]}<input value={perfil[nome]??''} maxLength={nome==='endereco'?300:100} onChange={e=>{campo(nome,e.target.value);if(['endereco','bairro','cidade'].includes(nome)){setPerfil(p=>({...p,latitude:null,longitude:null}));setLocais([]);}}} className="mt-1 w-full rounded-lg border border-on-surface/15 bg-surface-container p-2 text-sm"/></label>)}
 <button type="button" disabled={!perfil.endereco} onClick={()=>void buscar()} className="cursor-pointer rounded-lg bg-surface-container px-3 py-2 text-sm disabled:opacity-40">Localizar endereço</button>{locais.map((l,i)=><button type="button" key={i} onClick={()=>{setPerfil(p=>({...p,latitude:l.lat,longitude:l.lng}));setLocais([]);setMensagem('Localização selecionada. Salve para confirmar.');}} className="block w-full rounded-lg border border-primary/25 p-2 text-left text-xs hover:bg-primary/10">{l.endereco}</button>)}
 <div className="grid grid-cols-2 gap-3">{(['latitude','longitude'] as const).map(nome=><label key={nome} className="text-xs">{nome==='latitude'?'Latitude':'Longitude'}<input type="number" step="any" min={nome==='latitude'?-90:-180} max={nome==='latitude'?90:180} value={perfil[nome]??''} onChange={e=>campo(nome,e.target.value===''?null:Number(e.target.value))} className="mt-1 w-full rounded-lg bg-surface-container p-2"/></label>)}</div><label className="block text-xs">Sobre o integrante<textarea value={perfil.apresentacao??''} maxLength={1000} onChange={e=>campo('apresentacao',e.target.value)} className="mt-1 w-full rounded-lg bg-surface-container p-2"/></label>
 <div className="flex gap-2"><button type="submit" className="cursor-pointer rounded-xl bg-primary px-4 py-2 text-sm text-on-primary">Salvar perfil</button><button type="button" onClick={()=>{setPerfil(pessoa.perfil??vazio);setLocais([]);setMensagem('');setEditando(false);}} className="cursor-pointer rounded-xl bg-surface-container px-4 py-2 text-sm">Cancelar</button></div></fieldset></form>}{mensagem&&<p role="status" className="mt-3 text-sm text-primary">{mensagem}</p>}
 </div><div className="min-w-0 p-4 lg:sticky lg:top-0 lg:self-start"><MapaEquipe embutido aoLocalizarEvento={aoLocalizarEvento} evento={evento} pessoas={[pessoa]} demo={demo} fechar={()=>{}} perfil={()=>{}}/></div></div></JanelaEquipe>;
}
