"use client";
import {useEffect,useState} from "react";
type Cadastro={id:string;nome:string;funcao_origem:string|null;telefone:string|null;telefone_provisorio:boolean;email_origem:string|null;ativo:boolean;usuario_id:string|null};
export function PreCadastrosEquipe(){
 const [cadastros,setCadastros]=useState<Cadastro[]>([]);const [mensagem,setMensagem]=useState('Carregando…');const [busca,setBusca]=useState('');
 useEffect(()=>{let ativo=true;fetch('/api/operacao/pre-cadastros').then(async r=>{if(!r.ok)throw Error();return r.json();}).then(b=>{if(ativo){setCadastros(b.cadastros);setMensagem('');}}).catch(()=>{if(ativo)setMensagem('Não foi possível carregar os pré-cadastros.');});return()=>{ativo=false;};},[]);
 return <section className="space-y-4"><div><h2 className="font-headline-sm text-headline-sm">Pré-cadastros da equipe</h2><p className="mt-2 text-sm text-on-surface-variant">Funcionários importados da planilha. Os números demonstrativos estão bloqueados para OTP. Substitua cada um pelo WhatsApp real e conferido antes do beta; o acesso será vinculado quando a pessoa entrar com seu e-mail e confirmar o WhatsApp por código em Meu perfil.</p></div><input aria-label="Buscar pré-cadastro" placeholder="Buscar nome ou função" value={busca} onChange={e=>setBusca(e.target.value)} className="w-full rounded-xl bg-surface-container-high p-3"/>{mensagem&&<p role="status">{mensagem}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cadastros.filter(c=>(c.nome+' '+c.funcao_origem).toLocaleLowerCase('pt-BR').includes(busca.toLocaleLowerCase('pt-BR'))).map(c=><Card key={c.id} cadastro={c}/>)}</div></section>;
}
function Card({cadastro:c}:{cadastro:Cadastro}){
 const [telefone,setTelefone]=useState(c.telefone??'');const [email,setEmail]=useState(c.email_origem??'');const [provisorio,setProvisorio]=useState(c.telefone_provisorio);const [salvando,setSalvando]=useState(false);const [mensagem,setMensagem]=useState('');
 return <form className="rounded-2xl bg-surface-container-lowest p-4 space-y-3" onSubmit={async e=>{e.preventDefault();setSalvando(true);setMensagem('');try{const r=await fetch('/api/operacao/pre-cadastros',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:c.id,telefone,email})});const b=await r.json();if(r.ok&&typeof b.telefoneProvisorio==='boolean')setProvisorio(b.telefoneProvisorio);setMensagem(r.ok?(b.telefoneProvisorio?'Número demonstrativo mantido. Substitua pelo contato real antes do beta.':'Contato salvo. A confirmação será feita pelo titular.'):b.mensagem);}catch{setMensagem('Falha ao salvar.');}finally{setSalvando(false);}}}>
 <div><h3 className="font-semibold">{c.nome}</h3><p className="text-sm text-on-surface-variant">{c.funcao_origem||'Função não informada'}</p><span className="text-xs text-primary">{c.usuario_id?'Conta vinculada':!c.ativo?'Cadastro inativo':provisorio?'Número provisório · OTP bloqueado':telefone?'Aguardando confirmação do titular':'Sem WhatsApp na origem'}</span></div>
 <label className="block text-sm">WhatsApp com DDD<input disabled={!!c.usuario_id} type="tel" maxLength={30} value={telefone} onChange={e=>setTelefone(e.target.value)} className="mt-1 w-full rounded-lg bg-surface-container-high p-2"/></label>
 <label className="block text-sm">E-mail de referência (opcional)<input disabled={!!c.usuario_id} type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-lg bg-surface-container-high p-2"/></label>
 {!c.usuario_id&&<button disabled={salvando} className="rounded-lg bg-primary px-3 py-2 text-sm text-on-primary disabled:opacity-50">Salvar contato</button>}{mensagem&&<p role="status" className="text-sm">{mensagem}</p>}
 </form>;
}
