"use client";
import {memo,useEffect,useRef,useState} from "react";
import {useDraggable,useDndMonitor,DragOverlay} from "@dnd-kit/core";
import {createPortal} from "react-dom";
import {ChevronLeft,ChevronRight,Check,Pin,PinOff,MapPin,Sparkles,Star,UserRound,X} from "lucide-react";
import {AvatarPessoa} from "./AvatarPessoa";
import {ComposicaoEquipe} from "./ComposicaoEquipe";
import styles from "./PreviewSugestao.module.css";

import type {PessoaEquipe as Pessoa,SugestaoEquipe} from "./tipos";
export function PreviewSugestao({pessoas,vagas,disabled,aplicar,opcoes:alternativas,aoPerfil,aoGrupo,aoMapa}:{pessoas:Pessoa[];vagas:number;disabled:boolean;aplicar:(ids?:string[],lideres?:string[])=>void;opcoes:SugestaoEquipe[];aoPerfil:(p:Pessoa)=>void;aoGrupo?:(ids:string[]|null)=>void;aoMapa?:(ids:string[],lideres:string[])=>void}){
 const [pagina,setPagina]=useState(0),[arrastada,setArrastada]=useState<Pessoa|null>(null);
 const emArraste=useRef(false);
 const opcoes=alternativas.map(o=>o.pessoas);
 const atual=Math.min(pagina,Math.max(0,opcoes.length-1)),grupo=opcoes[atual]??[];
 const [aberto,setAberto]=useState(false),[fixado,setFixado]=useState(false),[topo,setTopo]=useState(80);
 const grupoChave=grupo.map(p=>p.id).join('|');
 const callbackGrupo=useRef(aoGrupo);callbackGrupo.current=aoGrupo;
 useEffect(()=>{callbackGrupo.current?.(aberto?grupoChave.split('|').filter(Boolean):null);return()=>callbackGrupo.current?.(null);},[aberto,grupoChave]);
 const painel=useRef<HTMLDivElement>(null),gatilho=useRef<HTMLButtonElement>(null);
 const espera=useRef<ReturnType<typeof setTimeout>|null>(null),porClique=useRef(false);
 function cancelarEspera(){if(espera.current){clearTimeout(espera.current);espera.current=null;}}
 function fechar(){cancelarEspera();porClique.current=false;setAberto(false);setFixado(false);gatilho.current?.focus();}
 function posicionar(){setTopo(Math.max(80,Math.min((gatilho.current?.getBoundingClientRect().bottom??72)+8,window.innerHeight-320)));}
 function entrar(){posicionar();cancelarEspera();if(!disabled&&pessoas.length)setAberto(true);}
 function sair(){cancelarEspera();if(!fixado&&!porClique.current&&!emArraste.current)espera.current=setTimeout(()=>setAberto(false),280);}
 useEffect(()=>()=>{if(espera.current)clearTimeout(espera.current);},[]);
 useEffect(()=>{if(!aberto)return;function fora(e:PointerEvent){if(!fixado&&!painel.current?.contains(e.target as Node)&&!gatilho.current?.contains(e.target as Node)){porClique.current=false;setAberto(false);}}function tecla(e:KeyboardEvent){if(e.key==="Escape"){porClique.current=false;setAberto(false);setFixado(false);gatilho.current?.focus();}}document.addEventListener("pointerdown",fora);document.addEventListener("keydown",tecla);return()=>{document.removeEventListener("pointerdown",fora);document.removeEventListener("keydown",tecla);};},[aberto,fixado]);
 useDndMonitor({onDragStart(e){if(e.active.data.current?.preview){cancelarEspera();emArraste.current=true;setArrastada(pessoas.find(p=>p.id===e.active.data.current?.pessoaId)??null);}},onDragEnd(){emArraste.current=false;setArrastada(null);},onDragCancel(){emArraste.current=false;setArrastada(null);}});
 const notas=grupo.flatMap(p=>p.nota===null?[]:[Number(p.nota)]);
 return <><button ref={gatilho} type="button" aria-haspopup="dialog" aria-expanded={aberto} disabled={disabled||!grupo.length} onPointerEnter={e=>{if(e.pointerType==="mouse")entrar();}} onPointerLeave={e=>{if(e.pointerType==="mouse")sair();}} onClick={()=>{posicionar();cancelarEspera();porClique.current=true;setAberto(true);requestAnimationFrame(()=>painel.current?.focus());}} className="flex h-8 items-center gap-1.5 whitespace-nowrap rounded-lg px-3 text-xs font-semibold text-primary transition-colors hover:bg-primary/15 disabled:opacity-40"><Sparkles size={14}/>Ver sugestão ({grupo.length})</button>
 {aberto&&createPortal(<div ref={painel} style={{top:topo,maxHeight:`calc(100dvh - ${topo+80}px)`}} onPointerEnter={cancelarEspera} onPointerLeave={e=>{if(e.pointerType==="mouse")sair();}} tabIndex={-1} role="dialog" aria-label="Preview da equipe sugerida" className={`${styles.preview} fixed top-20 right-4 z-[90] flex max-h-[calc(100dvh-11rem)] sm:max-h-[calc(100dvh-7rem)] w-[calc(100%-2rem)] max-w-xl flex-col overflow-hidden rounded-2xl border border-primary/30 bg-surface-container-lowest text-on-surface shadow-2xl outline-none sm:right-6`}>
 <div className="flex items-start gap-3 border-b border-on-surface/10 bg-primary/5 p-4"><span className="rounded-xl bg-primary/15 p-2.5 text-primary"><Sparkles size={22}/></span><div className="min-w-0 flex-1"><h2 className="font-bold">Uma equipe para este evento</h2><p className="mt-1 text-xs text-on-surface-variant">{grupo.length} de {vagas} vagas · Líderes primeiro · notas por função</p>{fixado&&<span className="mt-1 inline-block text-xs font-semibold text-primary">Preview fixado</span>}</div><button type="button" aria-label={fixado?"Desafixar preview":"Fixar preview"} aria-pressed={fixado} title={fixado?"Desafixar preview":"Manter aberto ao clicar fora"} onClick={()=>{cancelarEspera();setFixado(v=>!v);}} className={`rounded-lg p-2 transition-colors hover:bg-primary/15 ${fixado?"bg-primary/15 text-primary":"text-on-surface-variant"}`}>{fixado?<PinOff size={18}/>:<Pin size={18}/>}</button><button type="button" aria-label="Fechar preview" onClick={fechar} className="rounded-lg p-2 text-on-surface-variant hover:bg-primary/15"><X size={18}/></button></div>
 <div className="min-h-0 overflow-y-auto p-4"><div className="mb-3 flex items-center justify-between gap-2 text-xs"><span className="text-on-surface-variant">Sugestão por avaliações disponíveis</span><span className="flex items-center gap-1 font-semibold text-primary"><Star size={14} fill="currentColor"/>{notas.length?(notas.reduce((a,b)=>a+b,0)/notas.length).toFixed(1):"—"} média</span></div>{aoMapa&&<button type="button" onClick={()=>{aoMapa(grupo.map(p=>p.id),alternativas[atual]?.lideres??[]);fechar();}} className="mb-3 flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-primary/10 px-3 py-2 text-sm font-semibold text-primary"><MapPin size={16}/>Ver esta equipe no mapa</button>}<nav aria-label="Opções de equipe" className="mb-3 flex items-center justify-between gap-2"><button aria-label="Sugestão anterior" disabled={atual===0} onClick={()=>setPagina(atual-1)} className="cursor-pointer rounded-lg bg-surface-container p-2 disabled:opacity-30"><ChevronLeft size={18}/></button><div className="flex items-center gap-2">{opcoes.map((_,i)=><button key={i} aria-label={`Opção de equipe ${i+1}`} aria-pressed={atual===i} onClick={()=>setPagina(i)} className={`h-8 w-8 cursor-pointer rounded-full text-xs font-bold transition-colors ${atual===i?"bg-primary text-on-primary":"bg-surface-container"}`}>{i+1}</button>)}</div><button aria-label="Próxima sugestão" disabled={atual===opcoes.length-1} onClick={()=>setPagina(atual+1)} className="cursor-pointer rounded-lg bg-surface-container p-2 disabled:opacity-30"><ChevronRight size={18}/></button></nav><p className="mb-3 text-xs text-on-surface-variant">Opção {atual+1} de {opcoes.length} · Arraste uma pessoa para a equipe</p><ComposicaoEquipe pessoas={grupo} lideres={alternativas[atual]?.lideres??[]}/><div key={atual} className="grid grid-cols-2 gap-3 sm:grid-cols-3">{grupo.map(p=><PessoaArrastavel key={p.id} p={p} lider={alternativas[atual]?.lideres.includes(p.id)??false} disabled={disabled} aoPerfil={aoPerfil}/>)}</div></div>
 <div className="flex flex-wrap items-center justify-between gap-3 border-t border-on-surface/10 bg-surface-container-low p-4"><p className="max-w-64 text-xs text-on-surface-variant">Confira os nomes. Aplicar substitui a seleção atual; você ainda pode ajustar depois.</p><button type="button" disabled={disabled||!grupo.length} onClick={()=>{aplicar(grupo.map(p=>p.id),alternativas[atual]?.lideres);fechar();}} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-on-primary transition-transform active:scale-95 disabled:opacity-40"><Check size={17}/>Aplicar equipe</button></div>
 </div>,document.body)}{aberto&&createPortal(<DragOverlay zIndex={150} dropAnimation={null}>{arrastada?<div className="w-44 rounded-xl border border-primary bg-surface-container-lowest p-3 text-on-surface shadow-2xl"><ConteudoPessoa p={arrastada}/></div>:null}</DragOverlay>,document.body)}</>;
}

const ConteudoPessoa=memo(function ConteudoPessoa({p,lider}:{p:Pessoa;lider?:boolean}){return <><AvatarPessoa id={p.id} foto={p.foto_url} className="mb-3 h-16 w-16"/><h3 className="break-words text-sm font-semibold">{p.nome}</h3><p className="mt-1 text-xs text-primary">{lider?"Forno / líder":p.perfil?.garcom?"Atendimento":"Função não cadastrada"}</p><p className="mt-2 flex flex-wrap items-center gap-1 text-xs"><Star size={14} className="text-amber-500" fill="currentColor"/>{p.nota===null?"Sem nota":Number(p.nota).toFixed(1)}<span className="text-on-surface-variant">· {p.avaliacoes} avaliações</span></p></>;});
function PessoaArrastavel({p,disabled,aoPerfil,lider}:{p:Pessoa;lider:boolean;disabled:boolean;aoPerfil:(p:Pessoa)=>void}){const {attributes,listeners,setNodeRef,isDragging}=useDraggable({id:`preview:${p.id}`,data:{pessoaId:p.id,preview:true},disabled});return <article ref={setNodeRef} {...attributes} {...listeners} onContextMenu={e=>{e.preventDefault();aoPerfil(p);}} aria-label={`Arrastar ${p.nome} da sugestão`} className={`${styles.pessoa} ${styles.arrastavel} min-w-0 touch-none rounded-xl border border-on-surface/10 bg-surface-container-low p-3 ${isDragging?"opacity-30":""}`}><ConteudoPessoa p={p} lider={lider}/><button type="button" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()} onClick={()=>aoPerfil(p)} className="mt-2 rounded-lg bg-surface-container px-2 py-1 text-xs">Ver perfil</button></article>;}
