"use client";
import { useState } from "react";
import QRCode from "qrcode";
import { QrCode } from "lucide-react";
export const QR_DEMONSTRACAO = "cecchin:saida:demo:cecchin-demonstracao-saida";
export function QrEvento({evento,titulo,demo=false,compacto=false}:{evento:string;titulo:string;demo?:boolean;compacto?:boolean}) {
 const [imagem,setImagem]=useState("");const [erro,setErro]=useState("");const [ocupado,setOcupado]=useState(false);
 async function abrir(){setOcupado(true);setErro("");try{let codigo=QR_DEMONSTRACAO;if(!demo){const r=await fetch(`/api/operacao/embarque?evento=${evento}&qr=1`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.mensagem);codigo=d.codigo;}setImagem(await QRCode.toDataURL(codigo,{width:640,margin:4,errorCorrectionLevel:"M"}));}catch(e){setErro(e instanceof Error?e.message:"Falha ao gerar QR");}finally{setOcupado(false);}}
 function imprimir(){const janela=window.open("","_blank","width=800,height=900");if(!janela){setErro("Permita abrir a janela de impressão.");return;}const doc=janela.document;doc.title="QR de saída do evento";const style=doc.createElement("style");style.textContent="body{font:20px Arial;text-align:center;margin:32px;color:#000;background:#fff}img{width:130mm;max-width:90%}@page{size:A4;margin:20mm}";doc.head.append(style);const h=doc.createElement("h1");h.textContent=demo?"DEMONSTRAÇÃO - Cecchin Pizzas":"Cecchin Pizzas - Liberação de saída";const p=doc.createElement("p");p.textContent=titulo;const id=doc.createElement("p");id.textContent=`Evento: ${evento}`;const img=doc.createElement("img");img.alt="QR de liberação";img.onload=()=>{janela.focus();janela.print();};doc.body.append(h,p,id,img);img.src=imagem;const instrucao=doc.createElement("p");instrucao.textContent="Na Minha rota, conclua o checklist e toque em Liberar saída para ler este QR.";doc.body.append(instrucao);}
 return <>{compacto&&<button type="button" disabled={ocupado} aria-expanded={Boolean(imagem)} aria-label={imagem?"Recolher QR":"Mostrar QR para impressão"} onClick={()=>imagem?setImagem(""):void abrir()} className="absolute right-4 top-[4.5rem] flex h-20 w-20 flex-col items-center justify-center gap-1 rounded-xl bg-surface-container text-on-surface hover:bg-surface-container-high disabled:opacity-60"><QrCode className="h-7 w-7"/><span className="text-xs font-semibold">{ocupado?"Carregando...":imagem?"Recolher":"QR de saída"}</span></button>}{(!compacto||imagem||erro)&&<section className="scroll-mb-20 rounded-xl bg-surface-container-low p-4"><div className="text-sm leading-snug"><h3 className="mr-2 inline font-bold">QR de saída do evento</h3><p className="inline">{demo?"QR de demonstração, sem liberar eventos reais.":"Imprima e coloque no totem da base para a equipe confirmar o embarque."}</p></div>{!compacto&&<button disabled={ocupado} aria-expanded={Boolean(imagem)} onClick={()=>imagem?setImagem(""):void abrir()} className="mt-2 rounded-lg bg-surface-container px-4 py-2">{ocupado?"Carregando...":imagem?"Recolher QR":"Mostrar QR para impressão"}</button>}{erro&&<p role="alert" className="mt-2 text-error">{erro}</p>}{imagem&&<div className="mt-3 flex flex-col items-center gap-3"><img src={imagem} alt="QR de saída do evento" className="w-64 max-w-full rounded-lg bg-white"/><div className="flex flex-wrap justify-center gap-2"><button onClick={imprimir} className="rounded-lg bg-primary px-4 py-2 text-on-primary">Imprimir QR</button><a href={imagem} download={`qr-saida-${evento}.png`} className="rounded-lg bg-surface-container px-4 py-2">Baixar imagem</a></div></div>}</section>}</>;
}
