"use client";
import { useEffect, useState, type ReactNode } from "react";
import { useSearchParams } from "next/navigation";
import { LeitorQr } from "./LeitorQr";
import { QrEvento, QR_DEMONSTRACAO } from "./QrEvento";
export type EventoEmbarque={id:string;titulo:string;pessoas:number|null;forno:string|null;destino:string;horario:string};
const ITENS=[{id:"massas",nome:"Massas e quantidade planejada"},{id:"insumos",nome:"Molho, queijos e coberturas"},{id:"forno",nome:"Forno e pedras"},{id:"energia",nome:"Gás / alimentação do forno"},{id:"utensilios",nome:"Pás, tábuas e cortadores"},{id:"servico",nome:"Louças, guardanapos e descarte"},{id:"destino",nome:"Endereço e horário da saída"}];
export function RotaComChecklist({evento,children,demo=false,gestao=false}:{evento:EventoEmbarque|null;children:ReactNode;demo?:boolean;gestao?:boolean}){
 const params=useSearchParams();const [aba,setAba]=useState(params.get("aba")==="checklist"?"checklist":"rota");
 const [marcados,setMarcados]=useState<string[]>([]),[liberado,setLiberado]=useState<string|null>(null),[carregando,setCarregando]=useState(!demo),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(""),[leitor,setLeitor]=useState(false);
 useEffect(()=>{setAba(params.get("aba")==="checklist"?"checklist":"rota");},[params.get("aba")]);
 async function carregar(signal?:AbortSignal){if(!evento||demo)return;const r=await fetch(`/api/operacao/embarque?evento=${evento.id}`,{cache:"no-store",signal});const d=await r.json();if(!r.ok)throw new Error(d.mensagem);if(signal?.aborted)return;setMarcados(d.itens.filter((i:{conferido:boolean})=>i.conferido).map((i:{item:string})=>i.item));setLiberado(d.liberadoEm);}
 useEffect(()=>{setMarcados([]);setLiberado(null);setErro("");if(demo||!evento){setCarregando(false);return;}const controller=new AbortController();setCarregando(true);void carregar(controller.signal).catch(e=>{if(!controller.signal.aborted)setErro(e.message);}).finally(()=>{if(!controller.signal.aborted)setCarregando(false);});return()=>controller.abort();},[evento?.id,demo]);
 async function acao(corpo:Record<string,unknown>){const r=await fetch("/api/operacao/embarque",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({evento:evento?.id,...corpo})});const d=await r.json();if(!r.ok)throw new Error(d.mensagem);return d;}
 async function alternar(item:string){if(ocupado||liberado)return;setOcupado(true);setErro("");try{const conferido=!marcados.includes(item);if(!demo)await acao({acao:"conferir",item,conferido});setMarcados(antes=>conferido?[...antes,item]:antes.filter(i=>i!==item));}catch(e){setErro(e instanceof Error?e.message:"Falha ao salvar item");}finally{setOcupado(false);}}
 async function liberar(codigo:string){if(demo){if(codigo!==QR_DEMONSTRACAO)throw new Error("Leia o QR de demonstração desta tela");setLiberado(new Date().toISOString());}else{const d=await acao({acao:"liberar",codigo});setLiberado(d.resultado);}setLeitor(false);}
 if(!evento)return <>{children}</>;
 const completo=ITENS.every(i=>marcados.includes(i.id));
 return <div className="mx-auto flex max-w-4xl flex-col gap-4 pb-20">
 <nav aria-label="Etapas da minha rota" className="flex gap-2"><button aria-pressed={aba==="rota"} onClick={()=>setAba("rota")} className="rounded-full bg-surface-container px-4 py-2 aria-pressed:bg-primary aria-pressed:text-on-primary">Minha rota</button><button aria-pressed={aba==="checklist"} onClick={()=>setAba("checklist")} className="rounded-full bg-surface-container px-4 py-2 aria-pressed:bg-primary aria-pressed:text-on-primary">Checklist e saída</button></nav>
 <div className={aba==="rota"?"space-y-4":"hidden"}>{children}<button onClick={()=>setAba("checklist")} className="w-full rounded-xl bg-primary p-4 font-semibold text-on-primary">{liberado?"Ver saída liberada":"Conferir embarque e liberar saída"}</button></div>
 <div className={aba==="checklist"?"space-y-4":"hidden"}><section className="rounded-xl bg-surface-container-lowest p-5 shadow-sm"><h1 className="text-xl font-bold">Checklist de embarque</h1><p className="mt-1 text-sm text-on-surface-variant">{evento.titulo}</p>{demo&&<p className="mt-2 text-sm">Demonstração: as marcações não alteram eventos reais.</p>}
 {carregando?<p role="status" className="py-6">Carregando checklist...</p>:<><p className="my-4 text-sm">{marcados.length}/{ITENS.length} itens conferidos</p><div className="space-y-2">{ITENS.map(i=><label key={i.id} className="flex items-center gap-3 rounded-xl bg-surface-container-low p-4"><input type="checkbox" checked={marcados.includes(i.id)} disabled={ocupado||!!liberado} onChange={()=>void alternar(i.id)} className="h-5 w-5 accent-primary"/><span><span className="block font-medium">{i.nome}</span><span className="text-sm text-on-surface-variant">{i.id==="forno"?evento.forno??"Confirme o modelo com a base":i.id==="servico"?evento.pessoas===null?"Quantidade de pessoas não informada":`${evento.pessoas} pessoas`:i.id==="destino"?`${evento.destino} · ${evento.horario}`:null}</span></span></label>)}</div></>}
 {erro&&<div className="mt-3"><p role="alert" className="text-error">{erro}</p><button disabled={ocupado} onClick={()=>{setErro("");setCarregando(true);void carregar().catch(e=>setErro(e.message)).finally(()=>setCarregando(false));}} className="mt-2 rounded-lg bg-surface-container px-4 py-2">Recarregar checklist</button></div>}
 {liberado?<p role="status" className="mt-5 rounded-lg bg-primary/10 p-4 font-semibold">{demo?"Saída de demonstração liberada":"Saída liberada"} · {new Date(liberado).toLocaleString("pt-BR")}</p>:<button disabled={carregando||ocupado||!completo||!!erro} onClick={()=>setLeitor(true)} className="mt-5 w-full rounded-xl bg-primary p-4 font-semibold text-on-primary disabled:opacity-40">Liberar saída · ler QR Code</button>}
 </section>{(demo||gestao)&&<QrEvento evento={evento.id} titulo={evento.titulo} demo={demo}/>}</div>
 {leitor&&<LeitorQr aoLer={liberar} aoFechar={()=>setLeitor(false)}/>}
 </div>;
}
